In [70]:
!pip install requests pandas sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /Users/monish/Library/Python/3.9/lib/python/site-packages (2.32.3)
Requirement already satisfied: pandas in /Users/monish/Library/Python/3.9/lib/python/site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /Users/monish/Library/Python/3.9/lib/python/site-packages (2.0.50)
Requirement already satisfied: pymysql in /Users/monish/Library/Python/3.9/lib/python/site-packages (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from requests) (2024.12.14)
Requirement already satisfied: numpy>=1.22.4 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from pandas) (2024.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /Users/monish/Library/Python/3.9/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [71]:
my_airports = [
    "VIDP",  # Delhi
    "VOBL",  # Bangalore
    "VABB",  # Mumbai
    "VOMM",  # Chennai
    "VOHS",  # Hyderabad
    "VECC",  # Kolkata
    "VOCI",  # Kochi
    "VAAH",  # Ahmedabad
    "VOGO",  # Goa
    "VISA"   # Agartala
]

In [72]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/iata/LHR"

headers = {
	"x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'icao': 'EGLL', 'iata': 'LHR', 'shortName': 'Heathrow', 'fullName': 'London Heathrow', 'municipalityName': 'London', 'location': {'lat': 51.4706, 'lon': -0.461941}, 'elevation': {'meter': 25.3, 'km': 0.03, 'mile': 0.02, 'nm': 0.01, 'feet': 83.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.heathrow.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/London_Heathrow_Airport', 'twitter': 'https://x.com/HeathrowAirport', 'flightRadar': 'https://www.flightradar24.com/51.47,-0.46/14', 'googleMaps': 'https://www.google.com/maps/@51.470600,-0.461941,14z'}}

In [73]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/search/location"

querystring = {"lat":"40.688812","lon":"-74.044369","radiusKm":"50","limit":"10","withFlightInfoOnly":"false"}

headers = {
	"x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'searchBy': {'lat': 40.688812, 'lon': -74.04437}, 'count': 7, 'items': [{'icao': 'KEWR', 'iata': 'EWR', 'name': 'Newark Liberty', 'shortName': 'Liberty', 'municipalityName': 'Newark', 'location': {'lat': 40.6925, 'lon': -74.1687}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KLGA', 'iata': 'LGA', 'name': 'New York La Guardia', 'shortName': 'La Guardia', 'municipalityName': 'New York', 'location': {'lat': 40.7772, 'lon': -73.8726}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KTEB', 'iata': 'TEB', 'name': 'Teterboro', 'shortName': 'Teterboro', 'municipalityName': 'Teterboro', 'location': {'lat': 40.8501, 'lon': -74.0608}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KLDJ', 'iata': 'LDJ', 'name': 'Linden', 'shortName': 'Linden', 'municipalityName': 'Linden', 'location': {'lat': 40.6174, 'lon': -74.2446}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KJFK', 'iata': 'JFK', 'name': 'New York John F Kennedy', 'shortName': 'John F Kennedy', 'municipalityName': 'New York', 'location': {'lat': 40.6398, 'lon': -73.7789}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KCDW', 'iata': 'CDW', 'name': 'Caldwell Essex County', 'shortName': 'Essex County', 'municipalityName': 'Caldwell', 'location': {'lat': 40.8752, 'lon': -74.2814}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KMMU', 'iata': 'MMU', 'name': 'Morristown Municipal', 'shortName': 'Municipal', 'municipalityName': 'Morristown', 'location': {'lat': 40.7994, 'lon': -74.4149}, 'countryCode': 'US', 'timeZone': 'America/New_York'}]}

In [74]:
import requests
import pandas as pd

headers = {
    "x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
    "x-rapidapi-host": "aerodatabox.p.rapidapi.com",
    "Content-Type": "application/json"
}

In [75]:
airport_codes = [
    "DEL",
    "BLR",
    "BOM",
    "MAA",
    "HYD",
    "CCU",
    "COK",
    "AMD",
    "GOI",
    "IXA"
]

In [76]:
def fetch_airport(iata_code):

    url = f"https://aerodatabox.p.rapidapi.com/airports/iata/{iata_code}"

    response = requests.get(
        url,
        headers=headers
    )

    return response.json()

In [77]:
import time

airport_rows = []

for code in airport_codes:

    data = fetch_airport(code)

    if "message" in data:

        print(f"Skipping {code}: {data['message']}")

        continue

    airport_rows.append({

        "icao_code": data.get("icao"),

        "iata_code": data.get("iata"),

        "name": data.get("fullName"),

        "city": data.get("municipalityName"),

        "country": data.get("country", {}).get("name"),

        "continent": data.get("continent", {}).get("name"),

        "latitude": data.get("location", {}).get("lat"),

        "longitude": data.get("location", {}).get("lon"),

        "timezone": data.get("timeZone")

    })

    print(f"Loaded {code}")

    time.sleep(2)      # wait 2 seconds

Loaded DEL
Loaded BLR
Loaded BOM
Loaded MAA
Loaded HYD
Loaded CCU
Loaded COK
Loaded AMD
Loaded GOI
Loaded IXA

In [15]:
airport_df = pd.DataFrame(airport_rows)

airport_df.insert(
    0,
    "airport_id",
    range(1, len(airport_df)+1)
)

airport_df

,airport_id,icao_code,iata_code,name,city,country,continent,latitude,longitude,timezone
0,1,VIDP,DEL,New Delhi Indira Gandhi,New Delhi,India,Asia,28.566500,77.103100,Asia/Kolkata
1,2,VOBL,BLR,Bangalore Bengaluru,Bangalore,India,Asia,13.197899,77.706300,Asia/Kolkata
2,3,VABB,BOM,Mumbai Chhatrapati Shivaji,Mumbai,India,Asia,19.088700,72.867900,Asia/Kolkata
3,4,VOMM,MAA,Chennai,Chennai,India,Asia,12.990005,80.169300,Asia/Kolkata
4,5,VOHS,HYD,Hyderabad Rajiv Gandhi,Hyderabad,India,Asia,17.231318,78.429855,Asia/Kolkata
5,6,VECC,CCU,Kolkata Netaji Subhash Chandra Bose,Kolkata,India,Asia,22.654700,88.446700,Asia/Kolkata
6,7,VOCI,COK,Kochi Cochin,Kochi,India,Asia,10.152000,76.401900,Asia/Kolkata
7,8,VAAH,AMD,Ahmedabad Sardar Vallabhbhai Patel,Ahmedabad,India,Asia,23.077200,72.634700,Asia/Kolkata
8,9,VOGO,GOI,Vasco da Gama Dabolim,Vasco da Gama,India,Asia,15.380800,73.831400,Asia/Kolkata
9,10,VEAT,IXA,Agartala,Agartala,India,Asia,23.887000,91.240400,Asia/Kolkata

In [10]:
print(airport_df.columns.tolist())

['airport_id', 'icao_code', 'iata_code', 'name', 'city', 'country', 'continent', 'latitude', 'longitude', 'timezone']

In [68]:
#flights

In [79]:
import requests

url = "https://aerodatabox.p.rapidapi.com/flights/number/DL47/2025-01-01/2025-01-07"

querystring = {"dateLocalRole":"Both"}

headers = {
	"x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'message': "Specified date-time '01.01.2025 00:00' must not be earlier than 365 day(s) ago. There are no flights or flight-derived data available on this date."}

In [80]:
import requests
import time

def fetch_flights(iata_code):

    url = f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/{iata_code}"

    querystring = {
        "offsetMinutes":"-120",
        "durationMinutes":"720",
        "withLeg":"true",
        "direction":"Both",
        "withCancelled":"true",
        "withCodeshared":"true",
        "withCargo":"true",
        "withPrivate":"true",
        "withLocation":"false"
    }

    response = requests.get(
        url,
        headers=headers,
        params=querystring
    )

    time.sleep(2)

    return response.json()

In [81]:
flight_data = fetch_flights("DEL")

print(flight_data)

{'departures': [{'departure': {'scheduledTime': {'utc': '2026-06-05 04:59Z', 'local': '2026-06-05 10:29+05:30'}, 'revisedTime': {'utc': '2026-06-05 04:59Z', 'local': '2026-06-05 10:29+05:30'}, 'terminal': '1', 'gate': 'D39', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VIBK', 'iata': 'BKB', 'name': 'Bikaner', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 05:55Z', 'local': '2026-06-05 11:25+05:30'}, 'quality': ['Basic']}, 'number': '6E 7442', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'ATR 72'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:03Z', 'local': '2026-06-05 10:33+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:03Z', 'local': '2026-06-05 10:33+05:30'}, 'terminal': '1', 'gate': 'D4', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VABB', 'iata': 'BOM', 'name': 'Mumbai', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:05Z', 'local': '2026-06-05 12:35+05:30'}, 'revisedTime': {'utc': '2026-06-05 06:45Z', 'local': '2026-06-05 12:15+05:30'}, 'terminal': '2', 'baggageBelt': '1', 'quality': ['Basic', 'Live']}, 'number': '6E 6328', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:06Z', 'local': '2026-06-05 10:36+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:06Z', 'local': '2026-06-05 10:36+05:30'}, 'terminal': '1', 'gate': 'D42', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Srinagar'}, 'quality': []}, 'number': 'SG 160', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 737-800'}, 'airline': {'name': 'SpiceJet', 'iata': 'SG', 'icao': 'SEJ'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:08Z', 'local': '2026-06-05 10:38+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:08Z', 'local': '2026-06-05 10:38+05:30'}, 'terminal': '3', 'gate': '53', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VABB', 'iata': 'BOM', 'name': 'Mumbai', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:20Z', 'local': '2026-06-05 12:50+05:30'}, 'revisedTime': {'utc': '2026-06-05 06:46Z', 'local': '2026-06-05 12:16+05:30'}, 'terminal': '2', 'baggageBelt': '12', 'quality': ['Basic', 'Live']}, 'number': 'AI 2425', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:11Z', 'local': '2026-06-05 10:41+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:11Z', 'local': '2026-06-05 10:41+05:30'}, 'terminal': '1', 'gate': 'D13', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VECC', 'iata': 'CCU', 'name': 'Kolkata', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:00Z', 'local': '2026-06-05 12:30+05:30'}, 'quality': ['Basic']}, 'number': '6E 894', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:13Z', 'local': '2026-06-05 10:43+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:13Z', 'local': '2026-06-05 10:43+05:30'}, 'terminal': '3', 'gate': '39A', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VOHS', 'iata': 'HYD', 'name': 'Hyderabad', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:20Z', 'local': '2026-06-05 12:50+05:30'}, 'quality': ['Basic']}, 'number': 'AI 2859', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:14Z', 'local': '2026-06-05 10:44+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:14Z', 'local': '2026-06-05 10:44+05:30'}, 'terminal': '2', 'gate': 'T26', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VOGO', 'iata': 'GOI', 'name': 'Vasco da Gama', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:25Z', 'local': '2026-06-05 12:55+05:30'}, 'quality': ['Basic']}, 'number': '6E 2277', 'callSign': 'IGO2277', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-IMN', 'modeS': '8014E4', 'model': 'Airbus A321 NEO'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:16Z', 'local': '2026-06-05 10:46+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:16Z', 'local': '2026-06-05 10:46+05:30'}, 'terminal': '1', 'gate': 'D11', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VISR', 'iata': 'SXR', 'name': 'Srinagar', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 06:00Z', 'local': '2026-06-05 11:30+05:30'}, 'quality': ['Basic']}, 'number': 'IX 1980', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India Express', 'iata': 'IX', 'icao': 'AXB'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:17Z', 'local': '2026-06-05 10:47+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:17Z', 'local': '2026-06-05 10:47+05:30'}, 'terminal': '1', 'gate': 'D17', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VOBL', 'iata': 'BLR', 'name': 'Bangalore', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:50Z', 'local': '2026-06-05 13:20+05:30'}, 'revisedTime': {'utc': '2026-06-05 07:40Z', 'local': '2026-06-05 13:10+05:30'}, 'terminal': '2', 'baggageBelt': '8A', 'quality': ['Basic', 'Live']}, 'number': 'IX 2749', 'callSign': 'AXB2749', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-BXB', 'modeS': '8015EF', 'model': 'Boeing 737 MAX 8'}, 'airline': {'name': 'Air India Express', 'iata': 'IX', 'icao': 'AXB'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:19Z', 'local': '2026-06-05 10:49+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:19Z', 'local': '2026-06-05 10:49+05:30'}, 'terminal': '1', 'gate': 'D8', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VOGA', 'iata': 'GOX', 'name': 'Mopa', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:40Z', 'local': '2026-06-05 13:10+05:30'}, 'quality': ['Basic']}, 'number': 'QP 1817', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 737'}, 'airline': {'name': 'Starlight Airline', 'iata': 'QP', 'icao': 'SLT'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:20Z', 'local': '2026-06-05 10:50+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:20Z', 'local': '2026-06-05 10:50+05:30'}, 'terminal': '1', 'gate': 'D35', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Bilaspur'}, 'quality': []}, 'number': '9I 613', 'callSign': 'LLR613', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-UDA', 'modeS': '8014E9', 'model': 'ATR 42-600'}, 'airline': {'name': 'Alliance Air', 'iata': '9I', 'icao': 'LLR'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:21Z', 'local': '2026-06-05 10:51+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:21Z', 'local': '2026-06-05 10:51+05:30'}, 'terminal': '3', 'gate': '43', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VEPT', 'iata': 'PAT', 'name': 'Patna', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:00Z', 'local': '2026-06-05 12:30+05:30'}, 'quality': ['Basic']}, 'number': 'AI 2523', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:25Z', 'local': '2026-06-05 10:55+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:25Z', 'local': '2026-06-05 10:55+05:30'}, 'terminal': 'GA', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Bhubaneswar'}, 'quality': []}, 'number': 'ZZ 1030', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'airline': {'name': 'Private'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:25Z', 'local': '2026-06-05 10:55+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:25Z', 'local': '2026-06-05 10:55+05:30'}, 'terminal': '1', 'gate': 'D14', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VAUD', 'iata': 'UDR', 'name': 'Udaipur', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 06:25Z', 'local': '2026-06-05 11:55+05:30'}, 'quality': ['Basic']}, 'number': '6E 6376', 'callSign': 'IGO6376', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-IBW', 'modeS': '8015E6', 'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:26Z', 'local': '2026-06-05 10:56+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:26Z', 'local': '2026-06-05 10:56+05:30'}, 'terminal': '3', 'gate': '50', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VOGO', 'iata': 'GOI', 'name': 'Vasco da Gama', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 08:00Z', 'local': '2026-06-05 13:30+05:30'}, 'quality': ['Basic']}, 'number': 'AI 2627', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:28Z', 'local': '2026-06-05 10:58+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:28Z', 'local': '2026-06-05 10:58+05:30'}, 'terminal': '1', 'gate': 'D7', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VILH', 'iata': 'IXL', 'name': 'Leh', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 05:30Z', 'local': '2026-06-05 11:00+05:30'}, 'quality': ['Basic']}, 'number': '6E 6448', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:29Z', 'local': '2026-06-05 10:59+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:29Z', 'local': '2026-06-05 10:59+05:30'}, 'terminal': '1', 'gate': 'D12', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VEGT', 'iata': 'GAU', 'name': 'Guwahati', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 07:55Z', 'local': '2026-06-05 13:25+05:30'}, 'terminal': '2', 'quality': ['Basic']}, 'number': 'IX 1069', 'callSign': 'AXB1069', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-RTE', 'modeS': '801594', 'model': 'Airbus A321 NEO'}, 'airline': {'name': 'Air India Express', 'iata': 'IX', 'icao': 'AXB'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:29Z', 'local': '2026-06-05 10:59+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:29Z', 'local': '2026-06-05 10:59+05:30'}, 'terminal': '3', 'checkInDesk': 'K06-K14', 'gate': '19', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Dubai'}, 'quality': []}, 'number': 'EK 511', 'status': 'GateClosed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 777-300ER'}, 'airline': {'name': 'Emirates', 'iata': 'EK', 'icao': 'UAE'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:30Z', 'local': '2026-06-05 11:00+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:30Z', 'local': '2026-06-05 11:00+05:30'}, 'terminal': '3', 'gate': '39B', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Varanasi'}, 'quality': []}, 'number': '6E 5025', 'callSign': 'IGO5025', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-ICY', 'modeS': '801749', 'model': 'Airbus A321 NEO'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:31Z', 'local': '2026-06-05 11:01+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:31Z', 'local': '2026-06-05 11:01+05:30'}, 'terminal': '2', 'gate': 'T20', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Durgapur'}, 'quality': []}, 'number': '6E 2771', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:34Z', 'local': '2026-06-05 11:04+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:34Z', 'local': '2026-06-05 11:04+05:30'}, 'terminal': '1', 'gate': 'D3', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Ayodhya'}, 'quality': []}, 'number': 'QP 1607', 'status': 'GateClosed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 737'}, 'airline': {'name': 'Starlight Airline', 'iata': 'QP', 'icao': 'SLT'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:35Z', 'local': '2026-06-05 11:05+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:35Z', 'local': '2026-06-05 11:05+05:30'}, 'terminal': '1', 'gate': 'D23', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VELP', 'iata': 'AJL', 'name': 'Aizawl', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 08:10Z', 'local': '2026-06-05 13:40+05:30'}, 'quality': ['Basic']}, 'number': '6E 765', 'status': 'GateClosed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:38Z', 'local': '2026-06-05 11:08+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:38Z', 'local': '2026-06-05 11:08+05:30'}, 'terminal': '2', 'gate': 'T23', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Bhopal'}, 'quality': []}, 'number': 'AI 1723', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:39Z', 'local': '2026-06-05 11:09+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:39Z', 'local': '2026-06-05 11:09+05:30'}, 'terminal': '1', 'gate': 'D15', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Bengaluru Intl Airport'}, 'quality': []}, 'number': '6E 842', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:39Z', 'local': '2026-06-05 11:09+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:39Z', 'local': '2026-06-05 11:09+05:30'}, 'terminal': '2', 'gate': 'T33', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'VILK', 'iata': 'LKO', 'name': 'Lucknow', 'countryCode': 'in', 'timeZone': 'Asia/Kolkata'}, 'scheduledTime': {'utc': '2026-06-05 06:45Z', 'local': '2026-06-05 12:15+05:30'}, 'terminal': '3', 'quality': ['Basic']}, 'number': '6E 2147', 'status': 'GateClosed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:40Z', 'local': '2026-06-05 11:10+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:40Z', 'local': '2026-06-05 11:10+05:30'}, 'terminal': '2', 'gate': 'T29', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Cochin'}, 'quality': []}, 'number': 'AI 1763', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:41Z', 'local': '2026-06-05 11:11+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:41Z', 'local': '2026-06-05 11:11+05:30'}, 'terminal': '3', 'gate': '37A', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Bagdogra'}, 'quality': []}, 'number': '6E 5307', 'callSign': 'IGO5307', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'VT-IWZ', 'modeS': '8016B5', 'model': 'Airbus A320'}, 'airline': {'name': 'IndiGo', 'iata': '6E', 'icao': 'IGO'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'terminal': '3', 'checkInDesk': 'E08-E14', 'gate': '15A', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'EGLL', 'iata': 'LHR', 'name': 'London', 'countryCode': 'gb', 'timeZone': 'Europe/London'}, 'scheduledTime': {'utc': '2026-06-05 15:15Z', 'local': '2026-06-05 16:15+01:00'}, 'revisedTime': {'utc': '2026-06-05 15:15Z', 'local': '2026-06-05 16:15+01:00'}, 'terminal': '3', 'quality': ['Basic', 'Live']}, 'number': 'DL 5946', 'status': 'GateClosed', 'codeshareStatus': 'IsCodeshared', 'isCargo': False, 'aircraft': {'model': 'Boeing 787-9'}, 'airline': {'name': 'Delta Air Lines', 'iata': 'DL', 'icao': 'DAL'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'terminal': '3', 'checkInDesk': 'E08-E14', 'gate': '15A', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'icao': 'EGLL', 'iata': 'LHR', 'name': 'London', 'countryCode': 'gb', 'timeZone': 'Europe/London'}, 'scheduledTime': {'utc': '2026-06-05 15:15Z', 'local': '2026-06-05 16:15+01:00'}, 'revisedTime': {'utc': '2026-06-05 15:15Z', 'local': '2026-06-05 16:15+01:00'}, 'terminal': '3', 'quality': ['Basic', 'Live']}, 'number': 'VS 301', 'status': 'GateClosed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 787-9'}, 'airline': {'name': 'Virgin Atlantic', 'iata': 'VS', 'icao': 'VIR'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'terminal': '3', 'checkInDesk': 'H08-H14', 'gate': '9', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Doha'}, 'quality': []}, 'number': 'QR 571', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 787-8'}, 'airline': {'name': 'Qatar', 'iata': 'QR', 'icao': 'QTR'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:42Z', 'local': '2026-06-05 11:12+05:30'}, 'terminal': '2', 'gate': 'T31', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Ahmedabad'}, 'quality': []}, 'number': 'AI 1787', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Air India', 'iata': 'AI', 'icao': 'AIC'}}, {'departure': {'scheduledTime': {'utc': '2026-06-05 05:44Z', 'local': '2026-06-05 11:14+05:30'}, 'revisedTime': {'utc': '2026-06-05 05:44Z', 'local': '2026-06-05 11:14+05:30'}, 'terminal': '1', 'gate': 'D2', 'quality': ['Basic', 'Live']}, 'arrival': {'airport': {'name': 'Srinagar'}, 'quality': []}, 'number': 'IX 1074', 'status': 'Departed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model'

In [20]:
import time
import pandas as pd

airport_codes = [
    "DEL", "BLR", "BOM", "MAA", "HYD",
    "CCU", "COK", "AMD", "GOI", "IXA"
]

flight_rows = []

for airport in airport_codes:

    print("Loading", airport)

    try:
        flight_data = fetch_flights(airport)

        # ------------------
        # DEPARTURES
        # ------------------
        for flight in flight_data.get("departures", []):

            flight_rows.append({

                "flight_number":
                    flight.get("number"),

                "aircraft_registration":
                    flight.get("aircraft", {}).get("reg"),

                "aircraft_model":
                    flight.get("aircraft", {}).get("model"),

                "airline":
                    flight.get("airline", {}).get("name"),

                "airline_iata":
                    flight.get("airline", {}).get("iata"),

                "status":
                    flight.get("status"),

                "origin_airport":
                    airport,

                "destination_airport":
                    flight.get("arrival", {})
                          .get("airport", {})
                          .get("iata"),

                "departure_time":
                    flight.get("departure", {})
                          .get("scheduledTime", {})
                          .get("local"),

                "arrival_time":
                    flight.get("arrival", {})
                          .get("scheduledTime", {})
                          .get("local")
            })

        # ------------------
        # ARRIVALS
        # ------------------
        for flight in flight_data.get("arrivals", []):

            flight_rows.append({

                "flight_number":
                    flight.get("number"),

                "aircraft_registration":
                    flight.get("aircraft", {}).get("reg"),

                "aircraft_model":
                    flight.get("aircraft", {}).get("model"),

                "airline":
                    flight.get("airline", {}).get("name"),

                "airline_iata":
                    flight.get("airline", {}).get("iata"),

                "status":
                    flight.get("status"),

                "origin_airport":
                    flight.get("departure", {})
                          .get("airport", {})
                          .get("iata"),

                "destination_airport":
                    airport,

                "departure_time":
                    flight.get("departure", {})
                          .get("scheduledTime", {})
                          .get("local"),

                "arrival_time":
                    flight.get("arrival", {})
                          .get("scheduledTime", {})
                          .get("local")
            })

        print(
            airport,
            "Departures:", len(flight_data.get("departures", [])),
            "Arrivals:", len(flight_data.get("arrivals", []))
        )

        time.sleep(2)

    except Exception as e:
        print(f"Error loading {airport}: {e}")

# ------------------
# CREATE DATAFRAME
# ------------------

flights_df = pd.DataFrame(flight_rows)

# Optional flight_id
flights_df.insert(
    0,
    "flight_id",
    range(1, len(flights_df) + 1)
)

print("\nShape:", flights_df.shape)
print("\nColumns:")
print(flights_df.columns.tolist())

flights_df.head()

Loading DEL
DEL Departures: 437 Arrivals: 408
Loading BLR
BLR Departures: 261 Arrivals: 247
Loading BOM
BOM Departures: 249 Arrivals: 240
Loading MAA
MAA Departures: 114 Arrivals: 104
Loading HYD
HYD Departures: 155 Arrivals: 150
Loading CCU
CCU Departures: 110 Arrivals: 108
Loading COK
COK Departures: 43 Arrivals: 46
Loading AMD
AMD Departures: 64 Arrivals: 60
Loading GOI
GOI Departures: 32 Arrivals: 33
Loading IXA
IXA Departures: 15 Arrivals: 16

Shape: (2892, 11)

Columns:
['flight_id', 'flight_number', 'aircraft_registration', 'aircraft_model', 'airline', 'airline_iata', 'status', 'origin_airport', 'destination_airport', 'departure_time', 'arrival_time']

,flight_id,flight_number,aircraft_registration,aircraft_model,airline,airline_iata,status,origin_airport,destination_airport,departure_time,arrival_time
0,1,6E 1069,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,KBV,2026-06-04 07:15+05:30,2026-06-04 12:50+07:00
1,2,6E 810,VT-NCO,Airbus A320,IndiGo,6E,Departed,DEL,BLR,2026-06-04 07:16+05:30,2026-06-04 10:00+05:30
2,3,6E 6470,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,NMI,2026-06-04 07:17+05:30,2026-06-04 09:05+05:30
3,4,AI 213,VT-CIQ,Airbus A320,Air India,AI,Departed,DEL,KTM,2026-06-04 07:18+05:30,2026-06-04 09:05+05:45
4,5,AI 1767,None,Airbus A319,Air India,AI,Departed,DEL,JAI,2026-06-04 07:19+05:30,2026-06-04 08:15+05:30

In [82]:
print(flights_df.shape)

(2892, 11)

In [83]:
display(flights_df)

,flight_id,flight_number,aircraft_registration,aircraft_model,airline,airline_iata,status,origin_airport,destination_airport,departure_time,arrival_time
0,1,6E 1069,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,KBV,2026-06-04 07:15+05:30,2026-06-04 12:50+07:00
1,2,6E 810,VT-NCO,Airbus A320,IndiGo,6E,Departed,DEL,BLR,2026-06-04 07:16+05:30,2026-06-04 10:00+05:30
2,3,6E 6470,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,NMI,2026-06-04 07:17+05:30,2026-06-04 09:05+05:30
3,4,AI 213,VT-CIQ,Airbus A320,Air India,AI,Departed,DEL,KTM,2026-06-04 07:18+05:30,2026-06-04 09:05+05:45
4,5,AI 1767,None,Airbus A319,Air India,AI,Departed,DEL,JAI,2026-06-04 07:19+05:30,2026-06-04 08:15+05:30
...,...,...,...,...,...,...,...,...,...,...,...
2887,2888,6E 525,None,Airbus A320 NEO,IndiGo,6E,Expected,DIB,IXA,2026-06-04 14:35+05:30,2026-06-04 15:50+05:30
2888,2889,6E 6503,None,Airbus A320,IndiGo,6E,Expected,DEL,IXA,2026-06-04 13:25+05:30,2026-06-04 16:00+05:30
2889,2890,6E 6503,None,Airbus A320,IndiGo,6E,Expected,DEL,IXA,2026-06-04 13:25+05:30,2026-06-04 16:00+05:30
2890,2891,IX 1752,None,Airbus A320 NEO,Air India Express,IX,Expected,CCU,IXA,2026-06-04 15:05+05:30,2026-06-04 16:10+05:30
2891,2892,6E 485,None,Airbus A320 NEO,IndiGo,6E,Expected,CCU,IXA,2026-06-04 17:10+05:30,2026-06-04 18:10+05:30

In [23]:
import sqlite3

conn = sqlite3.connect("flight_project.db")

In [84]:
airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

flights_df.to_sql(
    "flights",
    conn,
    if_exists="replace",
    index=False
)

2892

In [85]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

             name
0        aircraft
1  airport_delays
2         airport
3         flights

In [78]:
#aircraft

In [86]:
import requests

url = "https://aerodatabox.p.rapidapi.com/aircrafts/reg/VP-BZP"

headers = {
	"x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'id': 14486, 'reg': 'VP-BZP', 'active': False, 'serial': '3631', 'hexIcao': '43BE88', 'airlineName': 'Aeroflot', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-214', 'numSeats': 180, 'rolloutDate': '2008-08-21', 'firstFlightDate': '2008-08-21', 'deliveryDate': '2008-09-02', 'registrationDate': '2008-09-02', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 17.8, 'verified': True, 'numRegistrations': 24}

In [27]:
import time
import requests

def fetch_aircraft(registration):

    url = f"https://aerodatabox.p.rapidapi.com/aircrafts/reg/{registration}"

    response = requests.get(url, headers=headers)

    time.sleep(2)

    return response.json()

In [87]:
print(flights_df.columns.tolist())

['flight_id', 'flight_number', 'aircraft_registration', 'aircraft_model', 'airline', 'airline_iata', 'status', 'origin_airport', 'destination_airport', 'departure_time', 'arrival_time']

In [88]:
registrations = (
    flights_df["aircraft_registration"]
    .dropna()
    .unique()
)

print("Unique registrations:", len(registrations))

Unique registrations: 305

In [111]:
import time
import pandas as pd

# Only first 30 registrations
registrations = (
    flights_df["aircraft_registration"]
    .dropna()
    .unique()[:100]
)

print("Registrations to fetch:", len(registrations))

aircraft_rows = []

for i, reg in enumerate(registrations, start=1):

    try:
        data = fetch_aircraft(reg)

        if not isinstance(data, dict):
            continue

        aircraft_rows.append({

            "registration": data.get("reg"),

            "model": data.get("typeName"),

            "manufacturer": data.get("productionLine"),

            "icao_type_code": data.get("icaoCode"),

            "owner": data.get("airlineName")

        })

        print(f"{i}/{len(registrations)} Loaded {reg}")

        time.sleep(0.5)

    except Exception as e:
        print(f"Error loading {reg}: {e}")

# Create DataFrame
aircraft_df = pd.DataFrame(aircraft_rows)

# Add aircraft_id column
aircraft_df.insert(
    0,
    "aircraft_id",
    range(1, len(aircraft_df) + 1)
)

print("\nAircraft Table Shape:", aircraft_df.shape)

aircraft_df.head()

Registrations to fetch: 100
1/100 Loaded VT-NCO
2/100 Loaded VT-CIQ
3/100 Loaded VT-ILC
4/100 Loaded VT-ILO
5/100 Loaded VT-IQH
6/100 Loaded VT-ISU
7/100 Loaded VT-IVB
8/100 Loaded VT-ISQ
9/100 Loaded VT-ANH
10/100 Loaded VT-BWW
11/100 Loaded VT-NCM
12/100 Loaded 9H-TJF
13/100 Loaded VT-NLB
14/100 Loaded VT-NCR
15/100 Loaded VT-EXG
16/100 Loaded VT-BWT
17/100 Loaded VT-NCB
Error loading VT-NHC: Expecting value: line 1 column 1 (char 0)
19/100 Loaded VT-TVG
20/100 Loaded VT-ANO
21/100 Loaded VT-TQQ
22/100 Loaded VT-NCH
23/100 Loaded VT-TNY
24/100 Loaded VT-SGG
25/100 Loaded VT-YBA
26/100 Loaded VT-RTQ
27/100 Loaded VT-IMD
28/100 Loaded VT-TQC
29/100 Loaded VT-ICV
30/100 Loaded VT-TQO
31/100 Loaded JA871J
32/100 Loaded VT-NHL
33/100 Loaded HZ-AK16
34/100 Loaded VT-ITG
35/100 Loaded VT-YAS
36/100 Loaded G-ZBJB
37/100 Loaded VT-TNW
38/100 Loaded VT-CID
39/100 Loaded HZ-AK11
40/100 Loaded VT-MXI
41/100 Loaded VT-YBI
42/100 Loaded VT-IXH
43/100 Loaded VT-BWU
44/100 Loaded VT-ATV
45/100 Loaded VT-IZB
46/100 Loaded VT-IQK
47/100 Loaded VT-MXD
48/100 Loaded VT-SQA
49/100 Loaded VT-NHD
50/100 Loaded G-VOOH
51/100 Loaded VT-IMB
52/100 Loaded VT-PPO
53/100 Loaded VT-AXU
54/100 Loaded VT-ATE
55/100 Loaded VT-ICN
56/100 Loaded VT-NHB
57/100 Loaded VT-ILN
58/100 Loaded VT-NHW
59/100 Loaded VT-ANL
60/100 Loaded VT-IQG
61/100 Loaded VT-EXA
62/100 Loaded VT-TSO
63/100 Loaded VT-TSD
64/100 Loaded VT-IPY
65/100 Loaded VT-ANT
66/100 Loaded VT-TQH
67/100 Loaded VT-ANQ
68/100 Loaded HS-TXP
69/100 Loaded VT-ICM
70/100 Loaded VT-BWG
71/100 Loaded VT-EXH
72/100 Loaded VT-NCP
Error loading VT-IPR: Expecting value: line 1 column 1 (char 0)
74/100 Loaded VT-TVA
75/100 Loaded VT-TVD
76/100 Loaded VT-ITR
Error loading VT-AWB: Expecting value: line 1 column 1 (char 0)
78/100 Loaded VT-JRF
79/100 Loaded VT-RTU
80/100 Loaded VT-ALP
81/100 Loaded JA869J
82/100 Loaded JA879A
83/100 Loaded VT-ALL
84/100 Loaded VT-ANS
85/100 Loaded VT-TSH
86/100 Loaded VT-ANN
87/100 Loaded C-FNNH
88/100 Loaded VT-IWQ
89/100 Loaded VT-YAV
90/100 Loaded VT-IUP
91/100 Loaded VT-ICD
92/100 Loaded VT-ILR
93/100 Loaded VT-BXM
94/100 Loaded VT-IXD
95/100 Loaded VT-YBD
96/100 Loaded VT-ICF
97/100 Loaded VT-ILP
Error loading VT-IKX: Expecting value: line 1 column 1 (char 0)
99/100 Loaded VT-IMY
100/100 Loaded VT-BDM

Aircraft Table Shape: (96, 6)

,aircraft_id,registration,model,manufacturer,icao_type_code,owner
0,1,VT-NCO,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
1,2,VT-CIQ,Airbus A320,Airbus A320,A320,Air India
2,3,VT-ILC,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
3,4,VT-ILO,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
4,5,VT-IQH,Airbus A320 NEO,Airbus A320 NEO,A20N,IndiGo

In [112]:
aircraft_df = pd.DataFrame(aircraft_rows)

aircraft_df.insert(
    0,
    "aircraft_id",
    range(1, len(aircraft_df) + 1)
)

aircraft_df

,aircraft_id,registration,model,manufacturer,icao_type_code,owner
0,1,VT-NCO,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
1,2,VT-CIQ,Airbus A320,Airbus A320,A320,Air India
2,3,VT-ILC,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
3,4,VT-ILO,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
4,5,VT-IQH,Airbus A320 NEO,Airbus A320 NEO,A20N,IndiGo
...,...,...,...,...,...,...
91,92,VT-YBD,Boeing 737 MAX 8,Boeing 737 MAX,B38M,Air G
92,93,VT-ICF,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
93,94,VT-ILP,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
94,95,VT-IMY,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
95,96,VT-BDM,Boeing 757-200,Boeing 757,B752,Blue Dart Aviation

In [113]:
aircraft_df.to_sql(
    "aircraft",
    conn,
    if_exists="replace",
    index=False
)

96

In [114]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

             name
0         flights
1  airport_delays
2         airport
3        aircraft

In [34]:
#delays

In [115]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/icao/KLAX/delays"

headers = {
	"x-rapidapi-key": "ddc5080faamshcc5edb6bc7f8031p192027jsn224b721b5f60",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'airportIcao': 'KLAX', 'from': {'utc': '2026-06-05 05:30Z', 'local': '2026-06-04 22:30-07:00'}, 'to': {'utc': '2026-06-05 07:30Z', 'local': '2026-06-05 00:30-07:00'}, 'departuresDelayInformation': {'numTotal': 90, 'numQualifiedTotal': 85, 'numCancelled': 0, 'medianDelay': '00:17:00', 'delayIndex': 0.94}, 'arrivalsDelayInformation': {'numTotal': 49, 'numQualifiedTotal': 48, 'numCancelled': 0, 'medianDelay': '-00:04:00', 'delayIndex': 0.0}}

In [36]:
import pandas as pd

delay_data = response.json()

airport_delays_df = pd.DataFrame([{

    "delay_id": 1,

    "airport_iata": delay_data.get("airportIcao", "")[1:],

    "delay_date": pd.Timestamp.now().date(),

    "total_flights":
        delay_data.get("departuresDelayInformation", {}).get("numTotal", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numTotal", 0),

    "delayed_flights":
        delay_data.get("departuresDelayInformation", {}).get("numQualifiedTotal", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numQualifiedTotal", 0),

    "avg_delay_min": None,

    "median_delay_min": None,

    "canceled_flights":
        delay_data.get("departuresDelayInformation", {}).get("numCancelled", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numCancelled", 0)

}])

airport_delays_df

,delay_id,airport_iata,delay_date,total_flights,delayed_flights,avg_delay_min,median_delay_min,canceled_flights
0,1,LAX,2026-06-04,170,148,None,None,0

In [116]:
airport_codes = [
    "KLAX", "KJFK", "EGLL", "VIDP", "VOBL",
    "VABB", "VOMM", "VOHS", "VECC", "OMDB"
]

delay_rows = []

for i, code in enumerate(airport_codes, start=1):

    url = f"https://aerodatabox.p.rapidapi.com/airports/icao/{code}/delays"

    response = requests.get(url, headers=headers)

    delay_data = response.json()

    delay_rows.append({

        "delay_id": i,

        "airport_iata": delay_data.get("airportIcao", "")[1:],

        "delay_date": pd.Timestamp.now().date(),

        "total_flights":
            delay_data.get("departuresDelayInformation", {}).get("numTotal", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numTotal", 0),

        "delayed_flights":
            delay_data.get("departuresDelayInformation", {}).get("numQualifiedTotal", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numQualifiedTotal", 0),

        "avg_delay_min": None,

        "median_delay_min": None,

        "canceled_flights":
            delay_data.get("departuresDelayInformation", {}).get("numCancelled", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numCancelled", 0)
    })

airport_delays_df = pd.DataFrame(delay_rows)

airport_delays_df

,delay_id,airport_iata,delay_date,total_flights,delayed_flights,avg_delay_min,median_delay_min,canceled_flights
0,1,LAX,2026-06-05,139,133,None,None,0
1,2,,2026-06-05,0,0,None,None,0
2,3,,2026-06-05,0,0,None,None,0
3,4,IDP,2026-06-05,158,158,None,None,1
4,5,,2026-06-05,0,0,None,None,0
5,6,ABB,2026-06-05,90,90,None,None,0
6,7,,2026-06-05,0,0,None,None,0
7,8,,2026-06-05,0,0,None,None,0
8,9,,2026-06-05,0,0,None,None,0
9,10,,2026-06-05,0,0,None,None,0

In [117]:
airport_delays_df.to_sql(
    "airport_delays",
    conn,
    if_exists="replace",
    index=False
)

10

In [118]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

             name
0         flights
1         airport
2        aircraft
3  airport_delays

In [93]:
#sql

In [119]:
airport_df.to_sql("airport", conn, if_exists="replace", index=False)

flights_df.to_sql("flights", conn, if_exists="replace", index=False)

aircraft_df.to_sql("aircraft", conn, if_exists="replace", index=False)

airport_delays_df.to_sql("airport_delays", conn, if_exists="replace", index=False)

10

1

In [120]:
for table in ["airport", "flights", "aircraft", "airport_delays"]:
    print(
        table,
        pd.read_sql_query(
            f"SELECT COUNT(*) AS cnt FROM {table}",
            conn
        )["cnt"][0]
    )

airport 162
flights 2892
aircraft 96
airport_delays 10

In [121]:
print("Unique origins:", flights_df["origin_airport"].nunique())
print("Unique destinations:", flights_df["destination_airport"].nunique())

print(sorted(flights_df["destination_airport"].dropna().unique()))

Unique origins: 146
Unique destinations: 147
['ADD', 'AGR', 'AJL', 'ALA', 'AMD', 'AMS', 'ATH', 'ATQ', 'AUH', 'BBI', 'BDQ', 'BEK', 'BHJ', 'BHO', 'BKB', 'BKK', 'BLR', 'BOM', 'BSZ', 'CCJ', 'CCU', 'CDG', 'CDP', 'CGN', 'CGO', 'CJB', 'CMB', 'CNN', 'COK', 'DAC', 'DAR', 'DBR', 'DED', 'DEL', 'DGH', 'DHM', 'DIB', 'DIU', 'DMU', 'DOH', 'DPS', 'DWC', 'DXB', 'DYU', 'EBB', 'FRA', 'GAU', 'GAY', 'GOI', 'GOP', 'GOX', 'GWL', 'HAN', 'HBX', 'HDO', 'HEL', 'HGI', 'HKT', 'HND', 'HSR', 'HYD', 'ICN', 'IDR', 'IMF', 'ISK', 'IST', 'IXA', 'IXB', 'IXC', 'IXD', 'IXE', 'IXG', 'IXJ', 'IXL', 'IXM', 'IXR', 'IXS', 'IXU', 'IXZ', 'JAF', 'JAI', 'JDH', 'JED', 'JGA', 'JLR', 'JRG', 'JRH', 'KBL', 'KBV', 'KJB', 'KLH', 'KNU', 'KQH', 'KTM', 'KUL', 'KWI', 'LEJ', 'LGW', 'LHR', 'LKO', 'MAA', 'MCT', 'MED', 'MLE', 'MNL', 'MRU', 'MXP', 'MYQ', 'NAG', 'NBO', 'NDC', 'NMI', 'NRT', 'PAT', 'PBH', 'PGH', 'PNQ', 'PNY', 'RGN', 'RJA', 'RPR', 'RUH', 'SAG', 'SAH', 'SEZ', 'SGN', 'SHJ', 'SHL', 'SIN', 'SSE', 'STV', 'SVO', 'SXR', 'SXV', 'SYD', 'TAS', 'TFU', 'TIR', 'TRV', 'TRZ', 'UDR', 'VDY', 'VGA', 'VIE', 'VNS', 'VTZ', 'WAW']

In [122]:
all_airports = (
    set(flights_df["origin_airport"].dropna())
    .union(
        set(flights_df["destination_airport"].dropna())
    )
)

known_airports = set(
    airport_df["iata_code"].dropna()
)

missing_airports = sorted(all_airports - known_airports)

print("Missing airports:", len(missing_airports))
print(missing_airports[:20])

Missing airports: 0
[]

In [98]:
extra_rows = []

for code in missing_airports:

    extra_rows.append({

        "airport_id": len(airport_df) + len(extra_rows) + 1,

        "icao_code": None,

        "iata_code": code,

        "name": code,

        "city": "Unknown",

        "country": "Unknown",

        "continent": "Unknown",

        "latitude": None,

        "longitude": None,

        "timezone": None
    })

airport_df = pd.concat(
    [airport_df, pd.DataFrame(extra_rows)],
    ignore_index=True
)

print(airport_df.shape)

(162, 10)

In [99]:
airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

162

In [123]:
for table in ["airport", "flights", "aircraft", "airport_delays"]:
    print(
        table,
        pd.read_sql_query(
            f"SELECT COUNT(*) AS cnt FROM {table}",
            conn
        )["cnt"][0]
    )

airport 162
flights 2892
aircraft 96
airport_delays 10

In [124]:
airport_df[["iata_code", "name"]]

    iata_code                        name
0         DEL     New Delhi Indira Gandhi
1         BLR         Bangalore Bengaluru
2         BOM  Mumbai Chhatrapati Shivaji
3         MAA                     Chennai
4         HYD      Hyderabad Rajiv Gandhi
..        ...                         ...
157       VTZ                         VTZ
158       WAW                         WAW
159       YVR                         YVR
160       YYZ                         YYZ
161       ZRH                         ZRH

[162 rows x 2 columns]

1. 1)Show the total number of flights for each aircraft model, listing the model and its count.

In [125]:
query = """
SELECT
    aircraft_model,
    COUNT(*) AS total_flights
FROM flights
GROUP BY aircraft_model
ORDER BY total_flights DESC;
"""

pd.read_sql_query(query, conn)

                           aircraft_model  total_flights
0                         Airbus A320 NEO            900
1                             Airbus A320            803
2                              Boeing 737            214
3                                  ATR 72            190
4                         Airbus A321 NEO            158
5                                    None            132
6                          Boeing 737-800            100
7                        Boeing 737 MAX 8             92
8                             Airbus A321             44
9                            Boeing 787-9             34
10                           Boeing 787-8             34
11                            Embraer 175             25
12                         Boeing 737-700             24
13                       Boeing 777-300ER             23
14                Airbus A320 (Sharklets)             18
15     Bombardier Dash 8 Q400 / DHC-8-400             14
16                            Airbus A319             13
17                        Airbus A350-900             11
18                        Airbus A330-200              7
19                         Boeing 777-300              6
20                         Boeing 777-200              5
21                         Boeing 737-900              5
22                             Boeing 777              4
23                        Airbus A330-900              4
24                        Airbus A330-300              4
25                             Boeing 787              3
26                McDonnell Douglas MD-83              2
27                             Boeing 767              2
28                           Boeing 747-8              2
29                         Boeing 737-500              2
30                              Avro RJ85              2
31                Airbus A321 (Sharklets)              2
32                            Airbus A310              2
33                    ATR 42/72 Freighter              2
34  De Havilland Canada DHC-8-400 Dash 8Q              1
35              Bombardier Dash 8 / DHC-8              1
36                       Boeing 777-200LR              1
37                         Boeing 757-200              1
38               Boeing 747-400 Freighter              1
39                         Boeing 747-400              1
40                             Boeing 747              1
41                       Airbus A350-1000              1
42                            Airbus A350              1

2 2)List all aircraft (registration, model) that have been assigned to more than 5 flights.

In [126]:
query = """
SELECT
    aircraft_model,
    COUNT(*) AS flight_count
FROM flights
GROUP BY aircraft_model
HAVING COUNT(*) > 5
ORDER BY flight_count DESC;
"""

pd.read_sql_query(query, conn)

                        aircraft_model  flight_count
0                      Airbus A320 NEO           900
1                          Airbus A320           803
2                           Boeing 737           214
3                               ATR 72           190
4                      Airbus A321 NEO           158
5                                 None           132
6                       Boeing 737-800           100
7                     Boeing 737 MAX 8            92
8                          Airbus A321            44
9                         Boeing 787-9            34
10                        Boeing 787-8            34
11                         Embraer 175            25
12                      Boeing 737-700            24
13                    Boeing 777-300ER            23
14             Airbus A320 (Sharklets)            18
15  Bombardier Dash 8 Q400 / DHC-8-400            14
16                         Airbus A319            13
17                     Airbus A350-900            11
18                     Airbus A330-200             7
19                      Boeing 777-300             6

3 For each airport, display its name and the number of outbound flights, but only for airports with more than 5 flights.

In [127]:
query = """
SELECT
    a.name,
    COUNT(*) AS outbound_flights
FROM flights f
JOIN airport a
    ON f.origin_airport = a.iata_code
GROUP BY a.name
HAVING COUNT(*) > 5
ORDER BY outbound_flights DESC;
"""

pd.read_sql_query(query, conn)

                                   name  outbound_flights
0               New Delhi Indira Gandhi               551
1                   Bangalore Bengaluru               350
2            Mumbai Chhatrapati Shivaji               336
3                Hyderabad Rajiv Gandhi               210
4   Kolkata Netaji Subhash Chandra Bose               162
..                                  ...               ...
56                                  BHO                 7
57                                  RJA                 6
58                                  JDH                 6
59                                  HSR                 6
60                                  BDQ                 6

[61 rows x 2 columns]

4 4)Find the top 3 destination airports (name, city) by number of arriving flights, sorted by count descending.

In [128]:
query = """
SELECT
    a.name,
    a.city,
    COUNT(*) AS arrivals
FROM flights f
JOIN airport a
    ON f.destination_airport = a.iata_code
GROUP BY a.name, a.city
ORDER BY arrivals DESC
LIMIT 3;
"""

pd.read_sql_query(query, conn)

                         name       city  arrivals
0     New Delhi Indira Gandhi  New Delhi       523
1  Mumbai Chhatrapati Shivaji     Mumbai       347
2         Bangalore Bengaluru  Bangalore       328

5 5)Show for each flight: number, origin, destination, and a label 'Domestic' or 'International' using CASE WHEN on country match.

In [129]:
query = """
SELECT
    f.flight_number,
    f.origin_airport,
    f.destination_airport,

    CASE
        WHEN ao.country = ad.country
            THEN 'Domestic'
        ELSE 'International'
    END AS flight_type

FROM flights f

LEFT JOIN airport ao
    ON f.origin_airport = ao.iata_code

LEFT JOIN airport ad
    ON f.destination_airport = ad.iata_code;
"""

pd.read_sql_query(query, conn)

     flight_number origin_airport destination_airport    flight_type
0          6E 1069            DEL                 KBV  International
1           6E 810            DEL                 BLR       Domestic
2          6E 6470            DEL                 NMI  International
3           AI 213            DEL                 KTM  International
4          AI 1767            DEL                 JAI  International
...            ...            ...                 ...            ...
2887        6E 525            DIB                 IXA  International
2888       6E 6503            DEL                 IXA       Domestic
2889       6E 6503            DEL                 IXA       Domestic
2890       IX 1752            CCU                 IXA       Domestic
2891        6E 485            CCU                 IXA       Domestic

[2892 rows x 4 columns]

6 6)Show the 5 most recent arrivals at “DEL” airport including flight number, aircraft, departure airport name, and arrival time, ordered by latest arrival.

In [130]:
query = """
SELECT
    flight_number,
    aircraft_model,
    origin_airport,
    arrival_time
FROM flights
WHERE destination_airport = 'DEL'
ORDER BY arrival_time DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

  flight_number   aircraft_model origin_airport            arrival_time
0        6E 613      Airbus A320            MAA  2026-06-04 21:55+05:30
1       6E 6043      Airbus A320            HYD  2026-06-04 21:40+05:30
2        AI 488  Airbus A320 NEO            GOI  2026-06-04 21:22+05:30
3       AI 2426  Airbus A320 NEO            BOM  2026-06-04 21:20+05:30
4        6E 317      Airbus A320            BOM  2026-06-04 21:15+05:30

7 7) Find all airports with no arriving flights (never used as a destination in flights table).

In [131]:
query = """
SELECT
    a.name,
    a.city,
    a.iata_code
FROM airport a
LEFT JOIN flights f
    ON a.iata_code = f.destination_airport
WHERE f.destination_airport IS NULL;
"""

pd.read_sql_query(query, conn)

   name     city iata_code
0   CAN  Unknown       CAN
1   CPH  Unknown       CPH
2   DMM  Unknown       DMM
3   EWR  Unknown       EWR
4   FCO  Unknown       FCO
5   HKG  Unknown       HKG
6   IXY  Unknown       IXY
7   JFK  Unknown       JFK
8   PAB  Unknown       PAB
9   PVG  Unknown       PVG
10  SAI  Unknown       SAI
11  SZX  Unknown       SZX
12  YVR  Unknown       YVR
13  YYZ  Unknown       YYZ
14  ZRH  Unknown       ZRH

8 8)For each airline, count the number of flights by status (e.g., 'On Time', 'Delayed', 'Cancelled') using CASE WHEN.

In [132]:
query = """
SELECT
    airline,

    SUM(CASE WHEN status='On Time' THEN 1 ELSE 0 END) AS on_time,

    SUM(CASE WHEN status='Delayed' THEN 1 ELSE 0 END) AS delayed,

    SUM(CASE WHEN status='Canceled' THEN 1 ELSE 0 END) AS canceled,

    COUNT(*) AS total_flights

FROM flights
GROUP BY airline
ORDER BY total_flights DESC;
"""

pd.read_sql_query(query, conn)

              airline  on_time  delayed  canceled  total_flights
0              IndiGo        0        5         4           1618
1           Air India        0       16         7            470
2   Air India Express        0        4         2            296
3   Starlight Airline        0        0         0            132
4            SpiceJet        0       15        11            100
..                ...      ...      ...       ...            ...
61          Blue Dart        0        0         0              1
62       Air Tanzania        0        0         0              1
63      Air Mauritius        0        0         0              1
64         Air Canada        0        0         0              1
65           Aeroflot        0        0         0              1

[66 rows x 5 columns]

9 9)Show all cancelled flights, with aircraft and both airports, ordered by departure time descending.

In [107]:
query = """
SELECT
    flight_number,
    aircraft_model,
    origin_airport,
    destination_airport,
    departure_time
FROM flights
WHERE status='Canceled'
ORDER BY departure_time DESC;
"""

pd.read_sql_query(query, conn)

,flight_number,aircraft_model,origin_airport,destination_airport,departure_time
0,SG 476,Boeing 737-800,DEL,BOM,2026-06-04 18:30+05:30
1,SG 476,Boeing 737-800,DEL,BOM,2026-06-04 18:30+05:30
2,6E 1235,Airbus A320 NEO,BOM,KWI,2026-06-04 17:15+05:30
3,SG 940,None,BOM,CCU,2026-06-04 17:05+05:30
4,SG 681,Boeing 737-800,BOM,PAT,2026-06-04 16:50+05:30
5,SG 880,None,BOM,AMD,2026-06-04 16:35+05:30
6,IX 2547,Boeing 737,VNS,BOM,2026-06-04 16:15+05:30
7,SG 1082,None,BOM,GOX,2026-06-04 16:05+05:30
8,6E 1807,None,DEL,None,2026-06-04 14:25+05:30
9,9I 861,None,DEL,None,2026-06-04 13:50+05:30
10,6E 841,None,BOM,IXE,2026-06-04 13:25+05:30
11,IX 1023,Boeing 737,BOM,VNS,2026-06-04 13:10+05:30
12,NH 829,Boeing 787-9,NRT,BOM,2026-06-04 11:15+09:00
13,AI 917,None,DEL,None,2026-06-04 09:50+05:30
14,AI 909,None,BOM,DXB,2026-06-04 08:25+05:30
15,SG 877,None,BOM,CCU,2026-06-04 08:20+05:30
16,AI 1765,None,DEL,None,2026-06-04 08:00+05:30
17,AI 1765,None,DEL,None,2026-06-04 08:00+05:30
18,AI 885,None,DEL,None,2026-06-04 07:25+05:30
19,SG 106,Boeing 737-700,None,DEL,None
20,6E 1808,None,None,DEL,None
21,AI 2214,Airbus A320 NEO,RUH,BOM,None
22,SG 876,None,CCU,BOM,None
23,SG 1082,None,IXY,BOM,None
24,SG 684,None,JAI,BOM,None
25,AI 910,None,DXB,BOM,None

 10 List all city pairs (origin-destination) that have more than 2 different aircraft models operating flights between them.

In [133]:
query = """
SELECT
    ao.city AS origin_city,
    ad.city AS destination_city,
    COUNT(DISTINCT f.aircraft_model) AS aircraft_models

FROM flights f

JOIN airport ao
    ON f.origin_airport = ao.iata_code

JOIN airport ad
    ON f.destination_airport = ad.iata_code

GROUP BY
    ao.city,
    ad.city

HAVING COUNT(DISTINCT f.aircraft_model) > 2

ORDER BY aircraft_models DESC;
"""

pd.read_sql_query(query, conn)

      origin_city destination_city  aircraft_models
0         Unknown        New Delhi               24
1       New Delhi          Unknown               23
2         Unknown        Bangalore               19
3       Bangalore          Unknown               17
4         Unknown           Mumbai               17
..            ...              ...              ...
58      New Delhi        Hyderabad                3
59      New Delhi          Kolkata                3
60        Unknown    Vasco da Gama                3
61  Vasco da Gama           Mumbai                3
62  Vasco da Gama          Unknown                3

[63 rows x 3 columns]

11
11) For each destination airport, compute the % of delayed flights (status='Delayed') among all arrivals, sorted by highest percentage.

In [134]:
query = """
SELECT
    destination_airport,

    ROUND(
        100.0 *
        SUM(CASE WHEN status='Delayed' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS delayed_percentage

FROM flights

GROUP BY destination_airport

ORDER BY delayed_percentage DESC;
"""

pd.read_sql_query(query, conn)

    destination_airport  delayed_percentage
0                   TFU              100.00
1                   DYU              100.00
2                   SXR               13.04
3                  None               12.70
4                   DEL                5.74
..                  ...                 ...
143                 AMD                0.00
144                 ALA                0.00
145                 AJL                0.00
146                 AGR                0.00
147                 ADD                0.00

[148 rows x 2 columns]

In [68]:
print(airport_df.shape)
print(flights_df.shape)
print(aircraft_df.shape)
print(airport_delays_df.shape)

(162, 10)
(2892, 11)
(29, 6)
(10, 8)

In [135]:
import sqlite3

conn = sqlite3.connect("aviation.db")

airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

flights_df.to_sql(
    "flights",
    conn,
    if_exists="replace",
    index=False
)

aircraft_df.to_sql(
    "aircraft",
    conn,
    if_exists="replace",
    index=False
)

airport_delays_df.to_sql(
    "airport_delays",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

print("All tables saved successfully")

All tables saved successfully

In [110]:
for table in ["airport", "flights", "aircraft", "airport_delays"]:
    cnt = pd.read_sql_query(
        f"SELECT COUNT(*) AS cnt FROM {table}",
        conn
    )
    print(table, cnt["cnt"][0])

airport 162
flights 2892
aircraft 29
airport_delays 10