<a href="https://colab.research.google.com/github/Monish731/GUVIPROJECT1/blob/main/vscodeguvi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install requests pandas sqlalchemy pymysql

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 2.3 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [3]:
my_airports = [
    "VIDP",  # Delhi
    "VOBL",  # Bangalore
    "VABB",  # Mumbai
    "VOMM",  # Chennai
    "VOHS",  # Hyderabad
    "VECC",  # Kolkata
    "VOCI",  # Kochi
    "VAAH",  # Ahmedabad
    "VOGO",  # Goa
    "VISA"   # Agartala
]

In [5]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/iata/LHR"

headers = {
	"x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'icao': 'EGLL', 'iata': 'LHR', 'shortName': 'Heathrow', 'fullName': 'London Heathrow', 'municipalityName': 'London', 'location': {'lat': 51.4706, 'lon': -0.461941}, 'elevation': {'meter': 25.3, 'km': 0.03, 'mile': 0.02, 'nm': 0.01, 'feet': 83.0}, 'country': {'code': 'GB', 'name': 'United Kingdom'}, 'continent': {'code': 'EU', 'name': 'Europe'}, 'timeZone': 'Europe/London', 'urls': {'webSite': 'http://www.heathrow.com/', 'wikipedia': 'https://en.wikipedia.org/wiki/London_Heathrow_Airport', 'twitter': 'https://x.com/HeathrowAirport', 'flightRadar': 'https://www.flightradar24.com/51.47,-0.46/14', 'googleMaps': 'https://www.google.com/maps/@51.470600,-0.461941,14z'}}

In [6]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/search/location"

querystring = {"lat":"40.688812","lon":"-74.044369","radiusKm":"50","limit":"10","withFlightInfoOnly":"false"}

headers = {
	"x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'searchBy': {'lat': 40.688812, 'lon': -74.04437}, 'count': 7, 'items': [{'icao': 'KEWR', 'iata': 'EWR', 'name': 'Newark Liberty', 'shortName': 'Liberty', 'municipalityName': 'Newark', 'location': {'lat': 40.6925, 'lon': -74.1687}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KLGA', 'iata': 'LGA', 'name': 'New York La Guardia', 'shortName': 'La Guardia', 'municipalityName': 'New York', 'location': {'lat': 40.7772, 'lon': -73.8726}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KTEB', 'iata': 'TEB', 'name': 'Teterboro', 'shortName': 'Teterboro', 'municipalityName': 'Teterboro', 'location': {'lat': 40.8501, 'lon': -74.0608}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KLDJ', 'iata': 'LDJ', 'name': 'Linden', 'shortName': 'Linden', 'municipalityName': 'Linden', 'location': {'lat': 40.6174, 'lon': -74.2446}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KJFK', 'iata': 'JFK', 'name': 'New York John F Kennedy', 'shortName': 'John F Kennedy', 'municipalityName': 'New York', 'location': {'lat': 40.6398, 'lon': -73.7789}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KCDW', 'iata': 'CDW', 'name': 'Caldwell Essex County', 'shortName': 'Essex County', 'municipalityName': 'Caldwell', 'location': {'lat': 40.8752, 'lon': -74.2814}, 'countryCode': 'US', 'timeZone': 'America/New_York'}, {'icao': 'KMMU', 'iata': 'MMU', 'name': 'Morristown Municipal', 'shortName': 'Municipal', 'municipalityName': 'Morristown', 'location': {'lat': 40.7994, 'lon': -74.4149}, 'countryCode': 'US', 'timeZone': 'America/New_York'}]}

In [7]:
import requests
import pandas as pd

headers = {
    "x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
    "x-rapidapi-host": "aerodatabox.p.rapidapi.com",
    "Content-Type": "application/json"
}

In [8]:
airport_codes = [
    "DEL",
    "BLR",
    "BOM",
    "MAA",
    "HYD",
    "CCU",
    "COK",
    "AMD",
    "GOI",
    "IXA"
]

In [9]:
def fetch_airport(iata_code):

    url = f"https://aerodatabox.p.rapidapi.com/airports/iata/{iata_code}"

    response = requests.get(
        url,
        headers=headers
    )

    return response.json()

In [10]:
import time

airport_rows = []

for code in airport_codes:

    data = fetch_airport(code)

    if "message" in data:

        print(f"Skipping {code}: {data['message']}")

        continue

    airport_rows.append({

        "icao_code": data.get("icao"),

        "iata_code": data.get("iata"),

        "name": data.get("fullName"),

        "city": data.get("municipalityName"),

        "country": data.get("country", {}).get("name"),

        "continent": data.get("continent", {}).get("name"),

        "latitude": data.get("location", {}).get("lat"),

        "longitude": data.get("location", {}).get("lon"),

        "timezone": data.get("timeZone")

    })

    print(f"Loaded {code}")

    time.sleep(2)      # wait 2 seconds

Loaded DEL
Loaded BLR
Loaded BOM
Loaded MAA
Loaded HYD
Loaded CCU
Loaded COK
Loaded AMD
Loaded GOI
Loaded IXA

In [11]:
airport_df = pd.DataFrame(airport_rows)

airport_df.insert(
    0,
    "airport_id",
    range(1, len(airport_df)+1)
)

airport_df

,airport_id,icao_code,iata_code,name,city,country,continent,latitude,longitude,timezone
0,1,VIDP,DEL,New Delhi Indira Gandhi,New Delhi,India,Asia,28.566500,77.103100,Asia/Kolkata
1,2,VOBL,BLR,Bangalore Bengaluru,Bangalore,India,Asia,13.197899,77.706300,Asia/Kolkata
2,3,VABB,BOM,Mumbai Chhatrapati Shivaji,Mumbai,India,Asia,19.088700,72.867900,Asia/Kolkata
3,4,VOMM,MAA,Chennai,Chennai,India,Asia,12.990005,80.169300,Asia/Kolkata
4,5,VOHS,HYD,Hyderabad Rajiv Gandhi,Hyderabad,India,Asia,17.231318,78.429855,Asia/Kolkata
5,6,VECC,CCU,Kolkata Netaji Subhash Chandra Bose,Kolkata,India,Asia,22.654700,88.446700,Asia/Kolkata
6,7,VOCI,COK,Kochi Cochin,Kochi,India,Asia,10.152000,76.401900,Asia/Kolkata
7,8,VAAH,AMD,Ahmedabad Sardar Vallabhbhai Patel,Ahmedabad,India,Asia,23.077200,72.634700,Asia/Kolkata
8,9,VOGO,GOI,Vasco da Gama Dabolim,Vasco da Gama,India,Asia,15.380800,73.831400,Asia/Kolkata
9,10,VEAT,IXA,Agartala,Agartala,India,Asia,23.887000,91.240400,Asia/Kolkata

In [12]:
print(airport_df.columns.tolist())

['airport_id', 'icao_code', 'iata_code', 'name', 'city', 'country', 'continent', 'latitude', 'longitude', 'timezone']

In [ ]:
#flights

In [13]:
import requests

url = "https://aerodatabox.p.rapidapi.com/flights/number/DL47/2025-01-01/2025-01-07"

querystring = {"dateLocalRole":"Both"}

headers = {
	"x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'message': "Specified date-time '01.01.2025 00:00' must not be earlier than 365 day(s) ago. There are no flights or flight-derived data available on this date."}

In [14]:
import requests
import time

def fetch_flights(iata_code):

    url = f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/{iata_code}"

    querystring = {
        "offsetMinutes":"-120",
        "durationMinutes":"720",
        "withLeg":"true",
        "direction":"Both",
        "withCancelled":"true",
        "withCodeshared":"true",
        "withCargo":"true",
        "withPrivate":"true",
        "withLocation":"false"
    }

    response = requests.get(
        url,
        headers=headers,
        params=querystring
    )

    time.sleep(2)

    return response.json()

In [16]:
import time
import pandas as pd

airport_codes = [
    "DEL", "BLR", "BOM", "MAA", "HYD",
    "CCU", "COK", "AMD", "GOI", "IXA"
]

flight_rows = []

for airport in airport_codes:

    print("Loading", airport)

    try:
        flight_data = fetch_flights(airport)

        # ------------------
        # DEPARTURES
        # ------------------
        for flight in flight_data.get("departures", []):

            flight_rows.append({

                "flight_number":
                    flight.get("number"),

                "aircraft_registration":
                    flight.get("aircraft", {}).get("reg"),

                "aircraft_model":
                    flight.get("aircraft", {}).get("model"),

                "airline":
                    flight.get("airline", {}).get("name"),

                "airline_iata":
                    flight.get("airline", {}).get("iata"),

                "status":
                    flight.get("status"),

                "origin_airport":
                    airport,

                "destination_airport":
                    flight.get("arrival", {})
                          .get("airport", {})
                          .get("iata"),

                "departure_time":
                    flight.get("departure", {})
                          .get("scheduledTime", {})
                          .get("local"),

                "arrival_time":
                    flight.get("arrival", {})
                          .get("scheduledTime", {})
                          .get("local")
            })

        # ------------------
        # ARRIVALS
        # ------------------
        for flight in flight_data.get("arrivals", []):

            flight_rows.append({

                "flight_number":
                    flight.get("number"),

                "aircraft_registration":
                    flight.get("aircraft", {}).get("reg"),

                "aircraft_model":
                    flight.get("aircraft", {}).get("model"),

                "airline":
                    flight.get("airline", {}).get("name"),

                "airline_iata":
                    flight.get("airline", {}).get("iata"),

                "status":
                    flight.get("status"),

                "origin_airport":
                    flight.get("departure", {})
                          .get("airport", {})
                          .get("iata"),

                "destination_airport":
                    airport,

                "departure_time":
                    flight.get("departure", {})
                          .get("scheduledTime", {})
                          .get("local"),

                "arrival_time":
                    flight.get("arrival", {})
                          .get("scheduledTime", {})
                          .get("local")
            })

        print(
            airport,
            "Departures:", len(flight_data.get("departures", [])),
            "Arrivals:", len(flight_data.get("arrivals", []))
        )

        time.sleep(2)

    except Exception as e:
        print(f"Error loading {airport}: {e}")

# ------------------
# CREATE DATAFRAME
# ------------------

flights_df = pd.DataFrame(flight_rows)

# Optional flight_id
flights_df.insert(
    0,
    "flight_id",
    range(1, len(flights_df) + 1)
)

print("\nShape:", flights_df.shape)
print("\nColumns:")
print(flights_df.columns.tolist())

flights_df.head()

Loading DEL
DEL Departures: 407 Arrivals: 393
Loading BLR
BLR Departures: 227 Arrivals: 241
Loading BOM
BOM Departures: 238 Arrivals: 256
Loading MAA
MAA Departures: 113 Arrivals: 112
Loading HYD
HYD Departures: 146 Arrivals: 161
Loading CCU
CCU Departures: 119 Arrivals: 120
Loading COK
COK Departures: 49 Arrivals: 46
Loading AMD
AMD Departures: 62 Arrivals: 63
Loading GOI
GOI Departures: 38 Arrivals: 39
Loading IXA
IXA Departures: 16 Arrivals: 17

Shape: (2863, 11)

Columns:
['flight_id', 'flight_number', 'aircraft_registration', 'aircraft_model', 'airline', 'airline_iata', 'status', 'origin_airport', 'destination_airport', 'departure_time', 'arrival_time']

,flight_id,flight_number,aircraft_registration,aircraft_model,airline,airline_iata,status,origin_airport,destination_airport,departure_time,arrival_time
0,1,6E 2298,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,JDH,2026-06-06 10:07+05:30,2026-06-06 10:55+05:30
1,2,6E 2132,VT-IBU,Airbus A321 NEO,IndiGo,6E,Departed,DEL,GOX,2026-06-06 10:09+05:30,2026-06-06 12:10+05:30
2,3,6E 2319,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,LKO,2026-06-06 10:11+05:30,2026-06-06 11:05+05:30
3,4,AI 2415,VT-CID,Airbus A320 NEO,Air India,AI,Departed,DEL,BLR,2026-06-06 10:13+05:30,2026-06-06 12:25+05:30
4,5,QP 1110,None,Boeing 737,Starlight Airline,QP,Departed,DEL,BOM,2026-06-06 10:13+05:30,2026-06-06 12:20+05:30

In [17]:
display(flights_df)

,flight_id,flight_number,aircraft_registration,aircraft_model,airline,airline_iata,status,origin_airport,destination_airport,departure_time,arrival_time
0,1,6E 2298,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,JDH,2026-06-06 10:07+05:30,2026-06-06 10:55+05:30
1,2,6E 2132,VT-IBU,Airbus A321 NEO,IndiGo,6E,Departed,DEL,GOX,2026-06-06 10:09+05:30,2026-06-06 12:10+05:30
2,3,6E 2319,None,Airbus A320 NEO,IndiGo,6E,Departed,DEL,LKO,2026-06-06 10:11+05:30,2026-06-06 11:05+05:30
3,4,AI 2415,VT-CID,Airbus A320 NEO,Air India,AI,Departed,DEL,BLR,2026-06-06 10:13+05:30,2026-06-06 12:25+05:30
4,5,QP 1110,None,Boeing 737,Starlight Airline,QP,Departed,DEL,BOM,2026-06-06 10:13+05:30,2026-06-06 12:20+05:30
...,...,...,...,...,...,...,...,...,...,...,...
2858,2859,6E 6503,None,Airbus A320,IndiGo,6E,Expected,DEL,IXA,2026-06-06 13:25+05:30,2026-06-06 16:00+05:30
2859,2860,6E 6503,None,Airbus A320,IndiGo,6E,Expected,DEL,IXA,2026-06-06 13:25+05:30,2026-06-06 16:00+05:30
2860,2861,IX 1752,None,Airbus A320 NEO,Air India Express,IX,Unknown,CCU,IXA,2026-06-06 15:05+05:30,2026-06-06 16:10+05:30
2861,2862,6E 485,None,Airbus A320 NEO,IndiGo,6E,Expected,CCU,IXA,2026-06-06 17:10+05:30,2026-06-06 18:10+05:30
2862,2863,6E 6173,None,Airbus A320,IndiGo,6E,Expected,CCU,IXA,2026-06-06 18:50+05:30,2026-06-06 19:50+05:30

In [18]:
import sqlite3

conn = sqlite3.connect("flight_project.db")

In [19]:
airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

flights_df.to_sql(
    "flights",
    conn,
    if_exists="replace",
    index=False
)

2863

In [ ]:
#aircraft

In [20]:
import requests

url = "https://aerodatabox.p.rapidapi.com/aircrafts/reg/VP-BZP"

headers = {
	"x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'id': 14486, 'reg': 'VP-BZP', 'active': False, 'serial': '3631', 'hexIcao': '43BE88', 'airlineName': 'Aeroflot', 'iataCodeShort': '320', 'icaoCode': 'A320', 'model': 'A320', 'modelCode': '320-214', 'numSeats': 180, 'rolloutDate': '2008-08-21', 'firstFlightDate': '2008-08-21', 'deliveryDate': '2008-09-02', 'registrationDate': '2008-09-02', 'typeName': 'Airbus A320', 'numEngines': 2, 'engineType': 'Jet', 'isFreighter': False, 'productionLine': 'Airbus A320', 'ageYears': 17.8, 'verified': True, 'numRegistrations': 24}

In [21]:
import time
import requests

def fetch_aircraft(registration):

    url = f"https://aerodatabox.p.rapidapi.com/aircrafts/reg/{registration}"

    response = requests.get(url, headers=headers)

    time.sleep(2)

    return response.json()

In [22]:
print(flights_df.columns.tolist())

['flight_id', 'flight_number', 'aircraft_registration', 'aircraft_model', 'airline', 'airline_iata', 'status', 'origin_airport', 'destination_airport', 'departure_time', 'arrival_time']

In [23]:
registrations = (
    flights_df["aircraft_registration"]
    .dropna()
    .unique()
)

print("Unique registrations:", len(registrations))

Unique registrations: 284

In [24]:
import time
import pandas as pd

# Only first 100 registrations
registrations = (
    flights_df["aircraft_registration"]
    .dropna()
    .unique()[:100]
)

print("Registrations to fetch:", len(registrations))

aircraft_rows = []

for i, reg in enumerate(registrations, start=1):

    try:
        data = fetch_aircraft(reg)

        if not isinstance(data, dict):
            continue

        aircraft_rows.append({

            "registration": data.get("reg"),

            "model": data.get("typeName"),

            "manufacturer": data.get("productionLine"),

            "icao_type_code": data.get("icaoCode"),

            "owner": data.get("airlineName")

        })

        print(f"{i}/{len(registrations)} Loaded {reg}")

        time.sleep(0.5)

    except Exception as e:
        print(f"Error loading {reg}: {e}")

# Create DataFrame
aircraft_df = pd.DataFrame(aircraft_rows)

# Add aircraft_id column
aircraft_df.insert(
    0,
    "aircraft_id",
    range(1, len(aircraft_df) + 1)
)

print("\nAircraft Table Shape:", aircraft_df.shape)

aircraft_df.head()

Registrations to fetch: 100
1/100 Loaded VT-IBU
2/100 Loaded VT-CID
3/100 Loaded VT-ICR
4/100 Loaded VT-IWV
5/100 Loaded VT-IMI
6/100 Loaded VT-IMH
7/100 Loaded VT-RNT
8/100 Loaded VT-ICN
9/100 Loaded VT-BXW
10/100 Loaded VT-NHX
Error loading VT-IFK: Expecting value: line 1 column 1 (char 0)
12/100 Loaded VT-CIG
13/100 Loaded VT-ANH
14/100 Loaded VT-IIO
15/100 Loaded VT-IVA
16/100 Loaded VT-NHD
17/100 Loaded VT-TNI
18/100 Loaded VT-NCV
19/100 Loaded VT-TSN
20/100 Loaded VT-NHL
21/100 Loaded VT-TNP
22/100 Loaded VT-NOB
23/100 Loaded 9N-AKX
24/100 Loaded VT-YBA
25/100 Loaded VT-NCJ
26/100 Loaded VT-EXP
27/100 Loaded VT-TQO
Error loading VT-NHC: Expecting value: line 1 column 1 (char 0)
29/100 Loaded VT-TNQ
30/100 Loaded 9H-TJF
31/100 Loaded VT-YAR
32/100 Loaded SU-GFK
33/100 Loaded VT-TSP
34/100 Loaded HS-TXN
35/100 Loaded VT-IBI
36/100 Loaded VT-ANQ
37/100 Loaded VT-NCE
38/100 Loaded VT-BXV
39/100 Loaded VT-IWQ
40/100 Loaded VT-IQK
41/100 Loaded VT-RTD
42/100 Loaded A5-RGG
43/100 Loaded VT-ITO
44/100 Loaded VT-ISX
45/100 Loaded VT-TNH
46/100 Loaded VT-TVD
47/100 Loaded VT-IPQ
48/100 Loaded VT-EXE
49/100 Loaded VT-RTB
50/100 Loaded VT-EXS
51/100 Loaded VT-ANA
52/100 Loaded VT-IOI
Error loading VT-IPK: Expecting value: line 1 column 1 (char 0)
54/100 Loaded VT-TQD
55/100 Loaded VT-IVY
56/100 Loaded VT-SLG
57/100 Loaded VT-IIB
58/100 Loaded VT-JRF
59/100 Loaded VT-JRE
60/100 Loaded VT-TVI
61/100 Loaded VT-TVH
62/100 Loaded VT-NHA
63/100 Loaded VT-ALX
64/100 Loaded VT-ALQ
65/100 Loaded JA872J
66/100 Loaded JA923A
Error loading VT-TQL: Expecting value: line 1 column 1 (char 0)
68/100 Loaded VT-ANW
69/100 Loaded VT-ANT
70/100 Loaded VT-ANS
71/100 Loaded C-FIUJ
72/100 Loaded VT-TQE
73/100 Loaded N833AA
74/100 Loaded VT-EXA
75/100 Loaded N29985
76/100 Loaded VT-IYD
77/100 Loaded VT-ILF
78/100 Loaded VT-IQG
79/100 Loaded VT-ILH
80/100 Loaded VT-IIZ
81/100 Loaded VT-IPU
82/100 Loaded VT-BXC
83/100 Loaded VT-IYU
84/100 Loaded VT-IMZ
85/100 Loaded VT-TNR
Error loading VT-BXY: Expecting value: line 1 column 1 (char 0)
87/100 Loaded VT-ICS
88/100 Loaded VT-BXB
89/100 Loaded VT-IRW
90/100 Loaded VT-ATH
91/100 Loaded VT-IRP
92/100 Loaded VT-IQJ
93/100 Loaded VT-IBH
94/100 Loaded VT-IXZ
95/100 Loaded VT-IYZ
96/100 Loaded VT-BWF
Error loading VT-YAF: Expecting value: line 1 column 1 (char 0)
98/100 Loaded VT-ITI
99/100 Loaded HZ-AQJ
100/100 Loaded VT-IBK

Aircraft Table Shape: (94, 6)

,aircraft_id,registration,model,manufacturer,icao_type_code,owner
0,1,VT-IBU,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
1,2,VT-CID,Airbus A320,Airbus A320,A320,Air India
2,3,VT-ICR,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
3,4,VT-IWV,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
4,5,VT-IMI,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo

In [25]:
aircraft_df = pd.DataFrame(aircraft_rows)

aircraft_df.insert(
    0,
    "aircraft_id",
    range(1, len(aircraft_df) + 1)
)

aircraft_df

,aircraft_id,registration,model,manufacturer,icao_type_code,owner
0,1,VT-IBU,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
1,2,VT-CID,Airbus A320,Airbus A320,A320,Air India
2,3,VT-ICR,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
3,4,VT-IWV,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
4,5,VT-IMI,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo
...,...,...,...,...,...,...
89,90,VT-IYZ,ATR 72,ATR 72,AT75,IndiGo
90,91,VT-BWF,Boeing 737 MAX 8,Boeing 737 MAX,B38M,Air India Express
91,92,VT-ITI,Airbus A320 NEO,Airbus A320 NEO,A20N,IndiGo
92,93,HZ-AQJ,Airbus A330,Airbus A330,A330,Saudi Arabian Airlines
93,94,VT-IBK,Airbus A321 NEO,Airbus A321 NEO,A21N,IndiGo

In [26]:
aircraft_df.to_sql(
    "aircraft",
    conn,
    if_exists="replace",
    index=False
)

94

In [ ]:
#delays

In [27]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/icao/KLAX/delays"

headers = {
	"x-rapidapi-key": "ca0c8d2747msh0271e1143ae0685p149f22jsne3ae29007e3a",
	"x-rapidapi-host": "aerodatabox.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

{'airportIcao': 'KLAX', 'from': {'utc': '2026-06-06 04:45Z', 'local': '2026-06-05 21:45-07:00'}, 'to': {'utc': '2026-06-06 06:45Z', 'local': '2026-06-05 23:45-07:00'}, 'departuresDelayInformation': {'numTotal': 89, 'numQualifiedTotal': 80, 'numCancelled': 0, 'medianDelay': '00:15:00', 'delayIndex': 0.83}, 'arrivalsDelayInformation': {'numTotal': 62, 'numQualifiedTotal': 57, 'numCancelled': 0, 'medianDelay': '-00:18:00', 'delayIndex': 0.0}}

In [28]:
import pandas as pd

delay_data = response.json()

airport_delays_df = pd.DataFrame([{

    "delay_id": 1,

    "airport_iata": delay_data.get("airportIcao", "")[1:],

    "delay_date": pd.Timestamp.now().date(),

    "total_flights":
        delay_data.get("departuresDelayInformation", {}).get("numTotal", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numTotal", 0),

    "delayed_flights":
        delay_data.get("departuresDelayInformation", {}).get("numQualifiedTotal", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numQualifiedTotal", 0),

    "avg_delay_min": None,

    "median_delay_min": None,

    "canceled_flights":
        delay_data.get("departuresDelayInformation", {}).get("numCancelled", 0) +
        delay_data.get("arrivalsDelayInformation", {}).get("numCancelled", 0)

}])

airport_delays_df

,delay_id,airport_iata,delay_date,total_flights,delayed_flights,avg_delay_min,median_delay_min,canceled_flights
0,1,LAX,2026-06-06,151,137,None,None,0

In [29]:
airport_codes = [
    "KLAX", "KJFK", "EGLL", "VIDP", "VOBL",
    "VABB", "VOMM", "VOHS", "VECC", "OMDB"
]

delay_rows = []

for i, code in enumerate(airport_codes, start=1):

    url = f"https://aerodatabox.p.rapidapi.com/airports/icao/{code}/delays"

    response = requests.get(url, headers=headers)

    delay_data = response.json()

    delay_rows.append({

        "delay_id": i,

        "airport_iata": delay_data.get("airportIcao", "")[1:],

        "delay_date": pd.Timestamp.now().date(),

        "total_flights":
            delay_data.get("departuresDelayInformation", {}).get("numTotal", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numTotal", 0),

        "delayed_flights":
            delay_data.get("departuresDelayInformation", {}).get("numQualifiedTotal", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numQualifiedTotal", 0),

        "avg_delay_min": None,

        "median_delay_min": None,

        "canceled_flights":
            delay_data.get("departuresDelayInformation", {}).get("numCancelled", 0) +
            delay_data.get("arrivalsDelayInformation", {}).get("numCancelled", 0)
    })

airport_delays_df = pd.DataFrame(delay_rows)

airport_delays_df

,delay_id,airport_iata,delay_date,total_flights,delayed_flights,avg_delay_min,median_delay_min,canceled_flights
0,1,LAX,2026-06-06,151,137,None,None,0
1,2,,2026-06-06,0,0,None,None,0
2,3,,2026-06-06,0,0,None,None,0
3,4,,2026-06-06,0,0,None,None,0
4,5,,2026-06-06,0,0,None,None,0
5,6,,2026-06-06,0,0,None,None,0
6,7,OMM,2026-06-06,38,0,None,None,0
7,8,,2026-06-06,0,0,None,None,0
8,9,,2026-06-06,0,0,None,None,0
9,10,,2026-06-06,0,0,None,None,0

In [30]:
airport_delays_df.to_sql(
    "airport_delays",
    conn,
    if_exists="replace",
    index=False
)

10

In [31]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

             name
0         airport
1         flights
2        aircraft
3  airport_delays

In [ ]:
#sql

In [32]:
airport_df.to_sql("airport", conn, if_exists="replace", index=False)

flights_df.to_sql("flights", conn, if_exists="replace", index=False)

aircraft_df.to_sql("aircraft", conn, if_exists="replace", index=False)

airport_delays_df.to_sql("airport_delays", conn, if_exists="replace", index=False)

10

1

In [33]:
for table in ["airport", "flights", "aircraft", "airport_delays"]:
    print(
        table,
        pd.read_sql_query(
            f"SELECT COUNT(*) AS cnt FROM {table}",
            conn
        )["cnt"][0]
    )

airport 10
flights 2863
aircraft 94
airport_delays 10

In [34]:
print("Unique origins:", flights_df["origin_airport"].nunique())
print("Unique destinations:", flights_df["destination_airport"].nunique())

print(sorted(flights_df["destination_airport"].dropna().unique()))

Unique origins: 136
Unique destinations: 130
['ADD', 'AGR', 'AJL', 'ALA', 'AMD', 'AMS', 'ATQ', 'AUH', 'BAH', 'BBI', 'BDQ', 'BHJ', 'BHO', 'BKB', 'BKK', 'BLR', 'BOM', 'CAI', 'CAN', 'CCJ', 'CCU', 'CDG', 'CDP', 'CJB', 'CMB', 'CNN', 'COK', 'DAC', 'DBR', 'DED', 'DEL', 'DGH', 'DHM', 'DIB', 'DIU', 'DMM', 'DMU', 'DOH', 'DPS', 'DXB', 'FCO', 'FRA', 'GAU', 'GAY', 'GOI', 'GOP', 'GOX', 'GWL', 'HAN', 'HBX', 'HDO', 'HGI', 'HJR', 'HKT', 'HND', 'HSR', 'HYD', 'IDR', 'IMF', 'ISK', 'IXA', 'IXB', 'IXC', 'IXD', 'IXE', 'IXG', 'IXJ', 'IXL', 'IXM', 'IXR', 'IXU', 'IXZ', 'JAF', 'JAI', 'JDH', 'JED', 'JGA', 'JLR', 'JRG', 'JRH', 'KJB', 'KLH', 'KNU', 'KTM', 'KUL', 'KWI', 'LHR', 'LKO', 'MAA', 'MCT', 'MED', 'MLE', 'MNL', 'MXP', 'MYQ', 'NAG', 'NDC', 'NMI', 'NRT', 'PAT', 'PBH', 'PGH', 'PNQ', 'PNY', 'PVG', 'RJA', 'RKT', 'RPR', 'RUH', 'RUP', 'SAG', 'SEZ', 'SGN', 'SHJ', 'SHL', 'SIN', 'SSE', 'STV', 'SXR', 'SXV', 'SYD', 'TAS', 'TIR', 'TRV', 'TRZ', 'UDR', 'VGA', 'VIE', 'VNS', 'VTZ']

In [35]:
all_airports = (
    set(flights_df["origin_airport"].dropna())
    .union(
        set(flights_df["destination_airport"].dropna())
    )
)

known_airports = set(
    airport_df["iata_code"].dropna()
)

missing_airports = sorted(all_airports - known_airports)

print("Missing airports:", len(missing_airports))
print(missing_airports[:20])

Missing airports: 136
['ADD', 'AGR', 'AJL', 'ALA', 'AMS', 'ATQ', 'AUH', 'BAH', 'BBI', 'BDQ', 'BHJ', 'BHO', 'BKB', 'BKK', 'CAI', 'CAN', 'CCJ', 'CDG', 'CDP', 'CGK']

In [36]:
extra_rows = []

for code in missing_airports:

    extra_rows.append({

        "airport_id": len(airport_df) + len(extra_rows) + 1,

        "icao_code": None,

        "iata_code": code,

        "name": code,

        "city": "Unknown",

        "country": "Unknown",

        "continent": "Unknown",

        "latitude": None,

        "longitude": None,

        "timezone": None
    })

airport_df = pd.concat(
    [airport_df, pd.DataFrame(extra_rows)],
    ignore_index=True
)

print(airport_df.shape)

(146, 10)

/tmp/ipykernel_2358/1588905615.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  airport_df = pd.concat(

In [37]:
airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

146

In [38]:
for table in ["airport", "flights", "aircraft", "airport_delays"]:
    print(
        table,
        pd.read_sql_query(
            f"SELECT COUNT(*) AS cnt FROM {table}",
            conn
        )["cnt"][0]
    )

airport 146
flights 2863
aircraft 94
airport_delays 10

In [39]:
airport_df[["iata_code", "name"]]

    iata_code                        name
0         DEL     New Delhi Indira Gandhi
1         BLR         Bangalore Bengaluru
2         BOM  Mumbai Chhatrapati Shivaji
3         MAA                     Chennai
4         HYD      Hyderabad Rajiv Gandhi
..        ...                         ...
141       VIE                         VIE
142       VNS                         VNS
143       VTZ                         VTZ
144       YVR                         YVR
145       YYZ                         YYZ

[146 rows x 2 columns]

1. 1)Show the total number of flights for each aircraft model, listing the model and its count.

In [40]:
query = """
SELECT
    aircraft_model,
    COUNT(*) AS total_flights
FROM flights
GROUP BY aircraft_model
ORDER BY total_flights DESC;
"""

pd.read_sql_query(query, conn)

                        aircraft_model  total_flights
0                      Airbus A320 NEO            924
1                          Airbus A320            803
2                           Boeing 737            211
3                               ATR 72            197
4                      Airbus A321 NEO            167
5                     Boeing 737 MAX 8             98
6                       Boeing 737-800             85
7                                 None             68
8                          Airbus A321             54
9                     Boeing 777-300ER             36
10                        Boeing 787-9             30
11             Airbus A320 (Sharklets)             29
12                        Boeing 787-8             28
13                      Boeing 737-700             24
14                         Embraer 175             19
15                     Airbus A350-900             17
16                         Airbus A319             11
17  Bombardier Dash 8 Q400 / DHC-8-400              8
18             Airbus A321 (Sharklets)              8
19                      Boeing 737-900              7
20                     Airbus A330-200              7
21                     Airbus A330-300              6
22                          Boeing 787              4
23                      Boeing 777-300              3
24                     Airbus A380-800              3
25                         Airbus A330              3
26           Bombardier Dash 8 / DHC-8              2
27                      Boeing 737-500              2
28                     Airbus A330-900              2
29                         Airbus A310              2
30                      Boeing 777-200              1
31                Boeing 777 Freighter              1
32                          Boeing 777              1
33                          Boeing 747              1
34                          ATR 42-300              1

2 2)List all aircraft (registration, model) that have been assigned to more than 5 flights.

In [41]:
query = """
SELECT
    aircraft_model,
    COUNT(*) AS flight_count
FROM flights
GROUP BY aircraft_model
HAVING COUNT(*) > 5
ORDER BY flight_count DESC;
"""

pd.read_sql_query(query, conn)

                        aircraft_model  flight_count
0                      Airbus A320 NEO           924
1                          Airbus A320           803
2                           Boeing 737           211
3                               ATR 72           197
4                      Airbus A321 NEO           167
5                     Boeing 737 MAX 8            98
6                       Boeing 737-800            85
7                                 None            68
8                          Airbus A321            54
9                     Boeing 777-300ER            36
10                        Boeing 787-9            30
11             Airbus A320 (Sharklets)            29
12                        Boeing 787-8            28
13                      Boeing 737-700            24
14                         Embraer 175            19
15                     Airbus A350-900            17
16                         Airbus A319            11
17  Bombardier Dash 8 Q400 / DHC-8-400             8
18             Airbus A321 (Sharklets)             8
19                      Boeing 737-900             7
20                     Airbus A330-200             7
21                     Airbus A330-300             6

3 For each airport, display its name and the number of outbound flights, but only for airports with more than 5 flights.

In [42]:
query = """
SELECT
    a.name,
    COUNT(*) AS outbound_flights
FROM flights f
JOIN airport a
    ON f.origin_airport = a.iata_code
GROUP BY a.name
HAVING COUNT(*) > 5
ORDER BY outbound_flights DESC;
"""

pd.read_sql_query(query, conn)

                                   name  outbound_flights
0               New Delhi Indira Gandhi               524
1            Mumbai Chhatrapati Shivaji               336
2                   Bangalore Bengaluru               306
3                Hyderabad Rajiv Gandhi               201
4   Kolkata Netaji Subhash Chandra Bose               177
..                                  ...               ...
57                                  RUH                 6
58                                  MCT                 6
59                                  JDH                 6
60                                  DIB                 6
61                                  DAC                 6

[62 rows x 2 columns]

4 4)Find the top 3 destination airports (name, city) by number of arriving flights, sorted by count descending.

In [43]:
query = """
SELECT
    a.name,
    a.city,
    COUNT(*) AS arrivals
FROM flights f
JOIN airport a
    ON f.destination_airport = a.iata_code
GROUP BY a.name, a.city
ORDER BY arrivals DESC
LIMIT 3;
"""

pd.read_sql_query(query, conn)

                         name       city  arrivals
0     New Delhi Indira Gandhi  New Delhi       517
1  Mumbai Chhatrapati Shivaji     Mumbai       357
2         Bangalore Bengaluru  Bangalore       336

5 5)Show for each flight: number, origin, destination, and a label 'Domestic' or 'International' using CASE WHEN on country match.

In [44]:
query = """
SELECT
    f.flight_number,
    f.origin_airport,
    f.destination_airport,

    CASE
        WHEN ao.country = ad.country
            THEN 'Domestic'
        ELSE 'International'
    END AS flight_type

FROM flights f

LEFT JOIN airport ao
    ON f.origin_airport = ao.iata_code

LEFT JOIN airport ad
    ON f.destination_airport = ad.iata_code;
"""

pd.read_sql_query(query, conn)

     flight_number origin_airport destination_airport    flight_type
0          6E 2298            DEL                 JDH  International
1          6E 2132            DEL                 GOX  International
2          6E 2319            DEL                 LKO  International
3          AI 2415            DEL                 BLR       Domestic
4          QP 1110            DEL                 BOM       Domestic
...            ...            ...                 ...            ...
2858       6E 6503            DEL                 IXA       Domestic
2859       6E 6503            DEL                 IXA       Domestic
2860       IX 1752            CCU                 IXA       Domestic
2861        6E 485            CCU                 IXA       Domestic
2862       6E 6173            CCU                 IXA       Domestic

[2863 rows x 4 columns]

6 6)Show the 5 most recent arrivals at “DEL” airport including flight number, aircraft, departure airport name, and arrival time, ordered by latest arrival.

In [45]:
query = """
SELECT
    flight_number,
    aircraft_model,
    origin_airport,
    arrival_time
FROM flights
WHERE destination_airport = 'DEL'
ORDER BY arrival_time DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

  flight_number   aircraft_model origin_airport            arrival_time
0       6E 6406  Airbus A321 NEO            BLR  2026-06-07 00:50+05:30
1        6E 951      Airbus A320            MAA  2026-06-07 00:35+05:30
2       AI 2710  Airbus A320 NEO            CCU  2026-06-07 00:35+05:30
3       AI 1828  Airbus A320 NEO            COK  2026-06-07 00:30+05:30
4       AI 2870  Airbus A320 NEO            HYD  2026-06-06 23:55+05:30

7 7) Find all airports with no arriving flights (never used as a destination in flights table).

In [46]:
query = """
SELECT
    a.name,
    a.city,
    a.iata_code
FROM airport a
LEFT JOIN flights f
    ON a.iata_code = f.destination_airport
WHERE f.destination_airport IS NULL;
"""

pd.read_sql_query(query, conn)

   name     city iata_code
0   CGK  Unknown       CGK
1   CGN  Unknown       CGN
2   CPH  Unknown       CPH
3   EWR  Unknown       EWR
4   HKG  Unknown       HKG
5   ICN  Unknown       ICN
6   IXI  Unknown       IXI
7   IXK  Unknown       IXK
8   JFK  Unknown       JFK
9   KBV  Unknown       KBV
10  MRU  Unknown       MRU
11  NBO  Unknown       NBO
12  TPE  Unknown       TPE
13  VDY  Unknown       VDY
14  YVR  Unknown       YVR
15  YYZ  Unknown       YYZ

8 8)For each airline, count the number of flights by status (e.g., 'On Time', 'Delayed', 'Cancelled') using CASE WHEN.

In [47]:
query = """
SELECT
    airline,

    SUM(CASE WHEN status='On Time' THEN 1 ELSE 0 END) AS on_time,

    SUM(CASE WHEN status='Delayed' THEN 1 ELSE 0 END) AS delayed,

    SUM(CASE WHEN status='Canceled' THEN 1 ELSE 0 END) AS canceled,

    COUNT(*) AS total_flights

FROM flights
GROUP BY airline
ORDER BY total_flights DESC;
"""

pd.read_sql_query(query, conn)

                            airline  on_time  delayed  canceled  total_flights
0                            IndiGo        0        2         3           1658
1                         Air India        0       11         2            462
2                 Air India Express        0        0         0            275
3                 Starlight Airline        0        1         0            144
4                          SpiceJet        0       18         2             79
5                   Shuttle America        0        1         0             24
6                            Etihad        0        0         0             23
7                          Emirates        0        0         0             22
8                      Alliance Air        0        0         0             18
9                         Singapore        0        0         0             15
10                         Oman Air        0        0         0             13
11                        SriLankan        0        0         0             10
12                    Saudi Arabian        0        1         0             10
13                          Private        0        0         0             10
14                         Malaysia        0        0         0              8
15                         Gulf Air        0        0         0              7
16                            Nepal        0        0         0              6
17                       Air Arabia        0        0         0              5
18                              ANA        0        0         0              5
19                  Virgin Atlantic        0        0         0              4
20                          Vietnam        0        0         0              4
21              Thai  International        0        0         0              4
22                            Fly91        0        0         0              4
23                 Biman Bangladesh        0        0         0              4
24                           Bhutan        0        0         0              4
25                        Ethiopian        0        2         0              3
26                         EgyptAir        0        0         0              3
27                          British        0        0         0              3
28                       Uzbekistan        0        0         0              2
29                   Thai AirAsia X        0        0         0              2
30                           Qantas        0        0         0              2
31                      Malindo Air        0        0         0              2
32                        Maldivian        0        0         0              2
33                           Kuwait        0        0         0              2
34  Japan Airlines International Co        0        0         0              2
35                          Drukair        0        0         0              2
36                   China Southern        0        0         2              2
37                    China Eastern        0        0         0              2
38                   Cathay Pacific        0        0         0              2
39                    Ariana Afghan        0        0         0              2
40                       Air Astana        0        0         0              2
41             Air Arabia Abu Dhabi        0        0         0              2
42                         flyadeal        0        0         0              1
43                           United        0        0         0              1
44                              UPS        0        0         0              1
45                            Qatar        0        0         0              1
46                         American        0        0         0              1
47                          AirAsia        0        0         0              1
48                       Air Canada        0        0         0              1
49                        AeroLogic        0        0         0              1

9 9)Show all cancelled flights, with aircraft and both airports, ordered by departure time descending.

In [48]:
query = """
SELECT
    flight_number,
    aircraft_model,
    origin_airport,
    destination_airport,
    departure_time
FROM flights
WHERE status='Canceled'
ORDER BY departure_time DESC;
"""

pd.read_sql_query(query, conn)

,flight_number,aircraft_model,origin_airport,destination_airport,departure_time
0,AI 983,None,BOM,DXB,2026-06-06 20:25+05:30
1,CZ 5070,None,BOM,CAN,2026-06-06 19:40+05:30
2,SG 555,Boeing 737-800,GOP,BOM,2026-06-06 18:15+05:30
3,6E 1235,Airbus A320,BOM,KWI,2026-06-06 17:15+05:30
4,SG 553,Boeing 737-800,BOM,GOP,2026-06-06 15:45+05:30
5,6E 1807,None,DEL,None,2026-06-06 14:25+05:30
6,AI 1850,Airbus A320 NEO,None,DEL,None
7,6E 1808,None,None,DEL,None
8,CZ 5069,None,CAN,BOM,None

 10 List all city pairs (origin-destination) that have more than 2 different aircraft models operating flights between them.

In [49]:
query = """
SELECT
    ao.city AS origin_city,
    ad.city AS destination_city,
    COUNT(DISTINCT f.aircraft_model) AS aircraft_models

FROM flights f

JOIN airport ao
    ON f.origin_airport = ao.iata_code

JOIN airport ad
    ON f.destination_airport = ad.iata_code

GROUP BY
    ao.city,
    ad.city

HAVING COUNT(DISTINCT f.aircraft_model) > 2

ORDER BY aircraft_models DESC;
"""

pd.read_sql_query(query, conn)

      origin_city destination_city  aircraft_models
0         Unknown        New Delhi               21
1       New Delhi          Unknown               20
2         Unknown        Bangalore               18
3         Unknown           Mumbai               18
4       Bangalore          Unknown               16
..            ...              ...              ...
60         Mumbai          Chennai                3
61      New Delhi          Kolkata                3
62        Unknown    Vasco da Gama                3
63  Vasco da Gama        New Delhi                3
64  Vasco da Gama          Unknown                3

[65 rows x 3 columns]

11
11) For each destination airport, compute the % of delayed flights (status='Delayed') among all arrivals, sorted by highest percentage.

In [50]:
query = """
SELECT
    destination_airport,

    ROUND(
        100.0 *
        SUM(CASE WHEN status='Delayed' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS delayed_percentage

FROM flights

GROUP BY destination_airport

ORDER BY delayed_percentage DESC;
"""

pd.read_sql_query(query, conn)

    destination_airport  delayed_percentage
0                   MNL              100.00
1                   ADD               50.00
2                   RUH               16.67
3                  None                9.62
4                   PAT                4.55
..                  ...                 ...
126                 AMS                0.00
127                 AMD                0.00
128                 ALA                0.00
129                 AJL                0.00
130                 AGR                0.00

[131 rows x 2 columns]

In [51]:
print(airport_df.shape)
print(flights_df.shape)
print(aircraft_df.shape)
print(airport_delays_df.shape)

(146, 10)
(2863, 11)
(94, 6)
(10, 8)

In [52]:
import sqlite3

conn = sqlite3.connect("aviation.db")

airport_df.to_sql(
    "airport",
    conn,
    if_exists="replace",
    index=False
)

flights_df.to_sql(
    "flights",
    conn,
    if_exists="replace",
    index=False
)

aircraft_df.to_sql(
    "aircraft",
    conn,
    if_exists="replace",
    index=False
)

airport_delays_df.to_sql(
    "airport_delays",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()

print("All tables saved successfully")

All tables saved successfully